### ISSUE TITLE
Kapacitor log overflow

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2627] opened 2017-12-20 21:48 UTC
![screenshot 2017-12-20 13 46 39_preview](https://user-images.githubusercontent.com/1477539/34230264-5fe0ba68-e58c-11e7-9d65-b1d934efb671.png)

**Comment by jaredscheib** [comment] 2018-01-16 22:02
dupe of #2673?

**Comment by nhaugo** [comment] 2018-01-17 17:00
Closing dupe

**Closed by nhaugo** 2018-01-17 17:00 UTC
Labels: polish
