### ISSUE TITLE
Adding new sources fails with "name and url required"

### ISSUE THREAD

**Issue by timraymond** [influxdata/chronograf#1049] opened 2017-03-23 15:19 UTC
To reproduce:

1. Visit the "Add a New Source" page.
2. Fill in information for a source that this instance of Chronograf has never seen before
3. Click "Add Source"

This is what results:

<img width="1432" alt="chronograf" src="https://cloud.githubusercontent.com/assets/288061/24254865/51a2a0c2-0fba-11e7-9acd-e3102cce3403.png">

Furthermore, there is a failing request to the backend with the same error in the JSON, so this is definitely a backend issue.

Attached HAR with the failing request:
[422-on-source-post.zip](https://github.com/influxdata/chronograf/files/865197/422-on-source-post.zip)

**Comment by timraymond** [comment] 2017-03-24 15:05
After upgrading Influx Enterprise to v1.2.2 from v1.0.4, this is no longer an issue for me. It's possible that this only occurs with older versions.

**Comment by nhaugo** [comment] 2017-03-27 20:58
I tested this against a 1.0.4 cluster and could not reproduce. closing.

**Closed by nhaugo** 2017-03-27 20:58 UTC
