### ISSUE TITLE
how to import pre-canned dashboard

### ISSUE THREAD

**Issue by jsaada** [influxdata/chronograf#780] opened 2017-01-16 10:08 UTC
hello,
not sure to understand how should i import the precanned dashboard in json format ?
any help appreciate
i'm using telegraf / influxdb in front of chronograf:

here is my telegraf config for input:

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  fieldpass = [ "usage*" ]
[[inputs.disk]]
  fielddrop = [ "inodes*" ]
  mount_points=["/","/home"]
[[inputs.diskio]]
  devices = ["sda2","sda3"]
  skip_serial_number = true
[[inputs.net]]
  interfaces = [ "eth0" ]
  fielddrop = [ "icmp*", "ip*", "tcp*", "udp*" ]
[[inputs.system]]

**Comment by goller** [comment] 2017-01-19 16:03
Hi @jsaada, thanks for writing in!  Sorry it took a bit to write back, we've been having a company get-together this week.

So, our goals with the precanned dashboards is that most common telegraf configurations are supported out-of-the-box (we aren't there yet though!). 

We currently don't have support for `inputs.diskio` in the release, but, I do have a PR for it for the next release here: https://github.com/influxdata/chronograf/pull/779

Sadly, we don't have `inputs.net` either, but, I do have an issue for it here: https://github.com/influxdata/chronograf/issues/775  My plan is to have `inputs.net` in the next release as well.

Currently, the documentation on how to make layouts is here: https://github.com/influxdata/chronograf/blob/master/docs/LAYOUT.md   

I'll try to carve out some time today to finish up the `inputs.net` pre-canned dashboard.  If you have suggestions about what you would like to see graphed, let us know!

**Comment by nhaugo** [comment] 2017-01-24 17:01
Closing as a duplicate of #779 and #775

**Closed by nhaugo** 2017-01-24 17:01 UTC

**Comment by jsaada** [comment] 2017-01-26 09:48
thanks for your answer,
i'll be patient for this feature to be fully ok ;)

best,
