### ISSUE TITLE
Invalid TickScript generated from Chronograf

### ISSUE THREAD

**Issue by rorist** [influxdata/chronograf#1531] opened 2017-05-23 12:22 UTC
Hello,

I'm using the latest version of the stack from the RPM release,

Chronograf `1.3.1.0`
Kapacitor `1.3.0`
InfluxDB `1.2.4`

on Red Hat Enterprise Linux Server release 7.1 (Maipo)
with the kernel `3.10.0-229.20.1.el7.x86_64`

When creating an alerting rule from Chronograf and adding a mean() function to a metric, I can't save the rule with the "There was a problem updating the rule" error.

Here's the query, `SELECT mean("usage_user") AS "mean_usage_user" FROM "telegraf"."autogen"."cpu" WHERE time > now() - 15m GROUP BY time(10s), "host"`

When digging into the http request, here the server error,
```
"parser: unexpected var line 11 char 3 in "		var name =". expected: "number","string","duration","identifier","TRUE","FALSE","==","(","-","!""
```

And the generated tick script,
```javascript
var db = 'telegraf'

var rp = 'autogen'

var measurement = 'cpu'

var groupBy = ['host']

var whereFilter = lambda: TRUE

var name = 'cpu usage user > 60'

var idVar = name + ':{{.Group}}'

var message = '{{.Time}} {{.Name}} is {{.Level}} on {{.Group.host}} (Value={{ index .Fields "value" }})'

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var outputDB = 'chronograf'

var outputRP = 'autogen'

var outputMeasurement = 'alerts'

var triggerType = 'threshold'

var details = '{{.Time}} {{.Name}} is {{.Level}} on {{.Group.host}} (Value={{ index .Fields "value" }})'

var crit = 60

var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    |eval(lambda: "usage_user")
        .as('value')

var trigger = data
    |alert()
        .crit(lambda: "value" > crit)
        .stateChangesOnly()
        .message(message)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .durationField(durationField)
        .details(details)
        .email('jean-baptiste.aubort@epfl.ch')

trigger
    |influxDBOut()
        .create()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement(outputMeasurement)
        .tag('alertName', name)
        .tag('triggerType', triggerType)

trigger
    |httpOut('output')
```

It's strange as the whereFilter should be correct according to the error message, allowing the value TRUE. 

Shouldn't the whereFilter contain the constraint defined in the query or probably the time filter is only for testing in the UI.. I'm very new to TICKScript and such, using the UI is one way to learn this so this is very unexpected :)

Cheers

**Comment by goller** [comment] 2017-05-23 12:55
Hi @rorist , thanks for writing in!  I'll work on reproducing it and figure out what is going on.

**Comment by goller** [comment] 2017-05-23 16:36
Ok I've been able to reproduce this:

1. Create a new alert without a function (so no group by)
2. Save the alert
3. Edit the alert
4. Update the field to be a mean 
5. Save
... failure

Looks like the groupBy time is not sent to the server.

**Comment by jaredscheib** [comment] 2017-05-25 00:55
@rorist La solution est près. Merci pour la rapportage.

**Comment by jaredscheib** [comment] 2017-05-27 00:35
@rorist A fix for this has been merged into master as of now.

**Comment by rorist** [comment] 2017-05-28 10:42
thanks for the very quick fix!

**Closed** 2017-06-01 17:49 UTC
Labels: bug
