### ISSUE TITLE
Web worker node module errors in console

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#4285] opened 2018-08-24 23:16 UTC
Getting a lot of these in the console for various node module files: `worker.js:39 Uncaught Error: Cannot find module '../node_modules/lodash/sumBy.js`. Appears to be related to web workers.

**Comment by chnn** [comment] 2018-08-29 18:12
may be fixed by https://github.com/influxdata/chronograf/pull/4315

**Comment by bthesorceror** [comment] 2018-08-31 20:53
Cannot reproduce, appears to be fixed.

**Closed by bthesorceror** 2018-08-31 20:53 UTC
Labels: chore
