### ISSUE TITLE
Add influxdb connection wizard on the first run is missing insecureSkipVerify json field

### ISSUE THREAD

**Issue by nunoalc** [influxdata/chronograf#1598] opened 2017-06-09 16:41 UTC
Description:
During the Chronograf first run, when trying to add the influxdb connection information and with the Unsafe SSL checked the request doesn't send the 'insecureSkipVerify' field to the Chronograf API. Doing so by Postman or curl, I managed to get past the wizard.

O.S: AWS lattest AMI
Chronograf version: 1.3.2.1
Installation: Through rpm installer

**Comment by nhaugo** [comment] 2017-10-10 16:46
Dupe of #2000

**Closed by nhaugo** 2017-10-10 16:46 UTC
Labels: discussion, in progress
