### ISSUE TITLE
Host lists and autoscaling

### ISSUE THREAD

**Issue by hasselrot** [influxdata/chronograf#1177] opened 2017-04-04 19:30 UTC
Hi!

Using autoscaling hosts, that come and go all day, creates a lot of clutter in the Host List.
A filter, or option to show "only active during the last 24 hours" or similar would be great!

![hostlist](https://cloud.githubusercontent.com/assets/16920380/24675011/e0adab0a-197d-11e7-9d76-5909295c80ff.png)

**Comment by nhaugo** [comment] 2017-08-30 22:32
Dupe of #1241

**Closed by nhaugo** 2017-08-30 22:32 UTC
Labels: discussion
