### ISSUE TITLE
 Chronograf (1.8.9.1) 未指明的错误。

### ISSUE THREAD

**Issue by menglayigexiang** [influxdata/chronograf#5658] opened 2021-01-12 01:06 UTC
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
Error: 未指明的错误。
   at yr (http://[::]:8888/src.6eaf9180.js:717:38874)
   at io (http://[::]:8888/src.6eaf9180.js:717:88783)
   at oo (http://[::]:8888/src.6eaf9180.js:717:91076)
   at uo (http://[::]:8888/src.6eaf9180.js:717:91439)
   at Yo (http://[::]:8888/src.6eaf9180.js:717:98524)
   at $o (http://[::]:8888/src.6eaf9180.js:717:97904)
   at jo (http://[::]:8888/src.6eaf9180.js:717:96925)
   at ho (http://[::]:8888/src.6eaf9180.js:717:95738)
   at kl.enqueueSetState (http://[::]:8888/src.6eaf9180.js:717:47534)
   at _.prototype.setState (http://[::]:8888/src.6eaf9180.js:708:1683)
```

**Comment by sranka** [comment] 2021-02-01 07:37
This looks like an internal error during updating of a detached React DOM element, such errors can be ignored. Closing, unless you can specify the circumstances of what was wrong from the user perspective and how to reproduce it.

**Closed by sranka** 2021-02-01 07:37 UTC
