### ISSUE TITLE
Adding a kapacitor alert rule adds a query to the Data Explorer

### ISSUE THREAD

**Issue by 121watts** [influxdata/chronograf#1772] opened 2017-07-24 23:27 UTC
#### Repro steps

- Remove all queries from DE
- Add a kapacitor alert rule
- Go back to data explorer
- See that query there

#### The problem
Kapacitor queryConfigs share the same reducer as the DataExplorer

Connect #1734

**Comment by sebastianarena** [comment] 2017-08-21 16:26
+1

**Comment by jaredscheib** [comment] 2017-08-21 17:54
@sebastianarena What are you +1'ing? This issue should have been resolved by the PR merged in above. Could you clarify your comment?

**Comment by sebastianarena** [comment] 2017-08-21 23:12
@jaredscheib The issue is still opened, and I'm acknowledging that this is still happening to me in the current version, in case I can be helpful to test anything now or when it's pushed to production to be fixed

**Comment by russorat** [comment] 2018-12-19 00:35
closing due to inactivity

**Closed by russorat** 2018-12-19 00:35 UTC
Labels: bug, delivered
