### ISSUE TITLE
Query builder doesn't fetch fields for non-default RPs

### ISSUE THREAD

**Issue by timraymond** [influxdata/chronograf#338] opened 2016-11-03 22:46 UTC
To reproduce:

1. Create a database with two retention policies. Make one of them the default.
2. Write data into both RPs.
3. In the Data Explorer, select the non-default retention policy under "Databases"
4. Select a measurement that you've written to under that RP.
5. Witness no fields.
6. Repeat 3 & 4 for the default retention policy and see that there are fields under the "Fields" tab.

I suspect this is because the query issued below to fetch those fields doesn't explicitly include the RP. It should look like `SHOW FIELD KEYS FROM "archive"."downsampled_cpu"` where "archive" is the non-default RP.

```json
{
  "query":"SHOW FIELD KEYS FROM \"downsampled_cpu\"",
  "db":"telegraf"
}
```

**Comment by nhaugo** [comment] 2017-01-05 19:54
This was fixed by pulling the rp into the measurement name

**Comment by timraymond** [comment] 2017-01-05 20:13
@nhaugo I'm still able to reproduce this on master

**Comment by 121watts** [comment] 2017-03-28 21:40
The issue now doesn't have anything to do with the RP being default or not.  The issue is that at some point (pre 1.2) measurements and tags were inserted into the database without fields.  Given the new line protocol in 1.2+, this should be impossible.

**Closed** 2017-03-28 21:40 UTC
Labels: bug, in progress
