### ISSUE TITLE
Dashboard Table Graph Format

### ISSUE THREAD

**Issue by cryptoquick** [influxdata/chronograf#1686] opened 2017-07-04 15:25 UTC
@nathanielc asked about displaying data in a table format, and we don't currently support that as a graph type on the dashboard.

**Comment by nhaugo** [comment] 2017-07-05 16:10
Dupe of #1031

**Comment by jaredscheib** [comment] 2017-08-31 00:22
Not quite @nhaugo – #1031 is about Data Explorer, whereas this one's about Dashboard. Re-opening for now (the other one was closed anyway).

**Comment by botzill** [comment] 2017-10-26 12:54
Hey guys,

Any plans to add such graph in the future ?

**Comment by nhaugo** [comment] 2017-10-26 13:05
@botzill yes, but it is not currently schedule for any particular release.

**Comment by nhaugo** [comment] 2017-11-03 19:58
See also #2246

**Comment by russorat** [comment] 2017-11-16 18:21
customer feedback: this would be really useful for "Top N" tables that could be used for identify bad actors. For example, i have a list of the top apps/ips/services that are making requests and I can investigate apps that are making way too many.

**Comment by hasselrot** [comment] 2017-12-13 12:31
Would be extremely useful!
Any updates on this?

**Comment by nhaugo** [comment] 2017-12-13 21:03
Hi @hasselrot,
I don't can't give you an exact timing, but it is near the top of the list for 2018

**Comment by 121watts** [comment] 2018-01-09 01:38
this package will be useful https://github.com/bvaughn/react-virtualized

**Comment by russorat** [comment] 2018-02-09 23:04
Initial Requirements:
 - [ ] A user shall be able to select to display their data as a table
 - [ ] A user shall be able to show or hide columns in the table
 - [ ] A user shall be able to sort table by any column
 - [ ] A user shall be able to override the name of each column
 - [ ] A user shall be able to correlate rows of the table with data from other graphs on the dash
 - [ ] A user shall be able to format the displayed timestamp

**Comment by alexpaxton** [comment] 2018-02-13 19:16
[table-graph-design--v2.pdf](https://github.com/influxdata/chronograf/files/1721285/table-graph-design--v2.pdf)

**Comment by alexpaxton** [comment] 2018-02-13 23:29
[table-graph-design--v3.pdf](https://github.com/influxdata/chronograf/files/1722079/table-graph-design--v3.pdf)

**Comment by evo7master** [comment] 2018-02-20 01:09
We often need to compare two datasets at the same point in time, so it
would be exceptionally useful to *not* mandate time series on one axis , but to allow comparison of multiple measurements at the same point in time in a matrix, see example below:

<img width="704" alt="screen shot 2018-02-20 at 12 08 16 pm" src="https://user-images.githubusercontent.com/14989118/36403100-d9aae096-1636-11e8-930e-ca5ca31b002d.png">

**Comment by russorat** [comment] 2018-02-20 17:48
thanks @evo7master ! we will see what we can do to tackle that use case.

**Comment by megastef** [comment] 2018-02-28 16:21
Please check ReactJS / Redux Data Table called Sematable [https://github.com/sematext/sematable](https://github.com/sematext/sematable). Sematable has probably all required features, is open source, and well maintained. The data table component is used in production for Sematext Cloud to show a large number of logs, events and alerts. 
Announcement Blog post (2016): https://sematext.com/blog/reactjs-redux-table-sematable/

**Comment by ischolten** [comment] 2018-02-28 22:26
Thanks so much @megastef! We are leaning towards react-virtualized at the moment due to the potential size of the data and the accompanying need for windowing/lazy-loading. But it's really nice to know that you are following our feature development. Thanks again!

**Comment by ebb-tide** [comment] 2018-03-02 00:38
- [x] Add react-visualized as dependency: https://bvaughn.github.io/react-virtualized/#/components/Grid 
- [x] Add Graphtable as a graph option in cell editor overlay.
- [x] Add basic Graphtable visualization options
- [x] Create Graphtable component

------ end of base requirements needed for init PR.  

- [ ] Graphtable: time format implementation. 
- [ ] Graphtable: lazyloading. 
- [ ] Graphtable: switching time axis vertical/ horizontal.
- [ ] Graphtable: columns sorting (with indicator)
	- from the vis options
	- from the table itself. 
- [ ] Graphtable: columns visibility toggle
- [ ] Graphtable: text wrapping. 
- [ ] Graphtable: series renaming. 
- [ ] Graphtable: highlight time range associated with crosshairs and bring in to view. 
- [ ] Graphtable: highlight cell on hover and trigger crosshairs on other cells. 
- [ ] Graphtable: fix top and left most col/row.
- [ ] Graphtable: thresholding colors individual cells text and background. 
- [ ] Graphtable: hide/unhide time column or row.

**Comment by alexpaxton** [comment] 2018-03-14 21:00
TableOptions shape

```
cell: {
  tableOptions: {
    timeFormat: '',
    verticalTimeAxis: false,
    sortBy: {
      internalName: '',
      displayName: '',
    },
    wrapping: '',
    columnNames: [],
}
```

**Comment by ebb-tide** [comment] 2018-03-22 00:28
* add props tableOptions in proptypes. 
* fix console error when only one field visible, and flip axes.
* implement test for table data transformation function. 
* Fix isempty data?
* clean up cellRenderer
* clean up render function in Tablegraph. 
* why so many me’s and why is it causing rerenders everywhere? 
* hover times between tables do not seem to match.
* check hoverTime calculations in tables that are sorted in non-time columns.

**Comment by stevebang** [comment] 2018-03-23 00:06
**Renamed "Fix First Column" to "Lock First Column"**

@russorat In the Table Controls, the option "Fix First Column" should be renamed to "Lock First Column". Here are a couple of examples where the term "lock" is used:
* Microsoft Excel: [Freeze panes to lock rows and columns](https://support.office.com/en-us/article/freeze-panes-to-lock-rows-and-columns-dab2ffc9-020d-4026-8121-67dd25f2508f) 
* SmartSheet: [Lock or Unlock Columns and Rows](https://help.smartsheet.com/articles/522077-locking-unlocking-columns-and-rows)

"Freeze" is often mentioned, but "lock" seems less ambiguous. When "freeze" is used, it is often documented as "to freeze (lock)" Or, as above, "Freeze panes to lock rows and columns".  I think that "lock" is the least confusing, and if others have to repeatedly explain "freeze" by saying "lock", enough said.  I did see in AirTable, their docs confusingly repeat the phrase "freeze (lock)" in explaining how to use the functionality, and at the end used the term "fixed" once. The term "fix" can be very confusing and difficult to translate meaningfully.

IBM in one instance refers to this as "Lock Column as Header" -- we could say "Lock First Column as Header", but I can see the first column being used for comparison and not as a header.

**Comment by russorat** [comment] 2018-03-23 19:24
also, eventually, we may be able to use influxql functions for this: https://github.com/influxdata/influxdb/issues/9625 https://github.com/influxdata/influxdb/issues/9626 https://github.com/influxdata/influxdb/issues/9627 https://github.com/influxdata/influxdb/issues/9628

**Comment by alexpaxton** [comment] 2018-03-23 19:49
![screen shot 2018-03-23 at 12 43 19 pm](https://user-images.githubusercontent.com/2433762/37850347-04357bb8-2e98-11e8-99cc-cc6c600c2995.png)

The UI for number formatting would be super simple (at least for this initial release)
The input would be `type="number"` to prevent users inputting decimals or non-numerical characters. You can also enforce a `max`/`min` from the HTML itself.

This input would either truncate the value or add `0`s to the end depending on the value

I'm also thinking that we should right-align cells with numerical data to ensure the decimal point is vertically aligned within each column. I arbitrarily put `3` as a reasonable default for decimal places to show.

I think in the future we'll move towards scoping some of these options (thresholds, decimal places, suffix/prefix) by column instead of applying to the whole table

**Comment by russorat** [comment] 2018-03-23 19:52
I think that makes sense

**Comment by russorat** [comment] 2018-04-02 22:46
- [ ] headers slightly off due to vertical scroll bar

![image](https://user-images.githubusercontent.com/4805997/38219965-f070060a-368c-11e8-9861-7ede643dcf94.png)

**Comment by russorat** [comment] 2018-04-03 18:49
- [ ] Need a way to reorder columns in the table
- [ ] Need a way to adjust the size of the columns. Sometimes they are really wide even if the data isn't
- [ ] Group by data should appear as a column duplicated for each row. This would allow you to use queries like `select host, usage_user from "telegraf"."autogen"."cpu" group by host limit 1` and get a table with two columns: host and usage_user.

**Comment by micw** [comment] 2018-04-04 09:01
Great work! Will there be an initial version available in 1.4.4?

**Comment by russorat** [comment] 2018-04-25 18:48
feedback from demo:
 - [ ] see if there is a way to fix the ugly scroll bars on firefox

**Comment by russorat** [comment] 2018-04-27 19:42
Found this issue with table graphs. When jumping to the CEO, the query and visualization jumps back to the old mode.

![kapture 2018-04-27 at 12 41 01](https://user-images.githubusercontent.com/4805997/39381881-7e99a082-4a18-11e8-9cb9-9dbe778514f9.gif)

**Comment by russorat** [comment] 2018-05-01 17:10
- [ ] need to fix the render of subqueries: `select sum("rate") from (SELECT difference("usage_user") AS "rate" FROM "kube-infra"."autogen"."cpu" WHERE time > :dashboardTime: GROUP BY *) WHERE "rate" > 0 GROUP BY cpu`

**Comment by russorat** [comment] 2018-05-03 17:15
Final few requests after using this for a little bit:
- [ ] number values in the table should be right aligned, all other values should be left aligned. In future releases, we may allow this to be configurable by columns.
- [ ] Do not highlight text values with thresholds. we may add a feature later specifically for non-numerical values
- [ ] when time column is hidden, stop syncing the scroll with other graphs.

**Comment by russorat** [comment] 2018-05-04 00:11
- [ ] left align number is being covered by the scroll bar. Could we shift it to the left a little bit?
![image](https://user-images.githubusercontent.com/4805997/39608166-77f2a8d8-4ef4-11e8-9f1e-b0f0b3720ae6.png)

- [ ] double clicking on a frozen left column highlights the entire column (or multiple rows). Is there a way to get it to highlight a single value? Not sure if it's OS and browser specific or some css thingy.

![kapture 2018-05-03 at 17 10 06](https://user-images.githubusercontent.com/4805997/39608236-e9a832ea-4ef4-11e8-887e-d3081d294239.gif)

**Closed** 2018-05-21 15:30 UTC
Labels: GraphTable, design
