### ISSUE TITLE
Chronograf not installed as a service

### ISSUE THREAD

**Issue by fabiopedrosa** [influxdata/chronograf#600] opened 2016-11-22 18:55 UTC
When installing chronograf at mine amazon instances (centos) I don't get a service for chronograf.

Installed using:
`wget https://dl.influxdata.com/chronograf/nightlies/chronograf-nightly.x86_64.rpm
sudo yum localinstall chronograf-nightly.x86_64.rpm`

**Comment by fabiopedrosa** [comment] 2016-11-22 18:58
Just noticed that if I run /usr/bin/chronograf once, the corresponding init.d entry is created.

**Comment by goller** [comment] 2016-11-22 19:08
hmm @rossmcdonald is that expected behavior for the RPMs?

**Comment by rossmcdonald** [comment] 2016-11-22 19:28
Hmm, not at all. @fabiopedrosa What version of CentOS are you running? I'll see if I can reproduce.

**Comment by fabiopedrosa** [comment] 2016-11-22 19:40
To be precise its a amazon ec2 image: Amazon Linux AMI release 2016.09

**Comment by nhaugo** [comment] 2017-01-04 02:47
@rossmcdonald did you get a chance to look at this?

@fabiopedrosa have you tried a recent version? Are you seeing the same behavior?

**Comment by rossmcdonald** [comment] 2017-01-10 21:53
@nhaugo I'm unable to reproduce this issue using Amazon Linux 2016.09.

@fabiopedrosa I'm going to go ahead and close this issue, but let us know if you continue to experience problems on Amazon Linux.

**Closed by rossmcdonald** 2017-01-10 21:53 UTC
Labels: build/packaging, in progress
