### ISSUE TITLE
Chronograf unable to load host list dashboard

### ISSUE THREAD

**Issue by jacksod1** [influxdata/chronograf#5240] opened 2019-07-26 21:17 UTC
I'm having an issue with Chronograf v 1.7.12 and Chrome 75.0.3770.80.  When I browse to the host list dashboard page the page will just load indefinitely.  I'm able successfully load the dashboard with Microsoft Edge and Mozilla Firefox.  WIth Chrome is just loads forever.

I have a Dev instance of Chronograf with the same version that works in Chrome.  However, the amount of hosts on that version is < 15 hosts.  My production instance of Chronograf has 50-60 hosts and has the issue with Chrome.

Chronograf is connecting to InfluxDB version 1.7.7.  There is a Loadbalancer (Traefik) sitting in front of Chronograf.

![image](https://user-images.githubusercontent.com/3721202/61981967-deea7600-afc0-11e9-82a6-656fbd0779d7.png)

**Comment by desa** [comment] 2019-07-30 16:56
hey @jacksod1 thanks for opening the issue. Would it be possible for you to send us the logs on the Chronograf server and the output in the browser console.

**Comment by tiancheng91** [comment] 2019-09-08 17:14
I have the same issue only in chrome, 

Call to `/chronograf/v1/sources/0/proxy` keeps in Stalled state and no response in chrome network.
No request log in chronograf service side.

**Comment by kd4pba** [comment] 2020-04-04 01:27
Ughh Seriously?  2 hours in searching and this is all I find, Dead ends.  Is Chronograf something that is serious or just flat broken?  Impossible to find anything but closed tickets

**Comment by sranka** [comment] 2021-08-30 05:45
There are several major fixes since chronograf 1.7.12. Some chronograf UI pages did not close properly server connections, it caused problems similar to the one reported herein. These issues are fixed in chronograf 1.9.0 . InfluxDB also went through several fixes and improvements since 1.7.7. Feel to reopen if you can reproduce it with the newest chronograf version (1.9.0).

**Closed by sranka** 2021-08-30 05:45 UTC
