### ISSUE TITLE
view as table broken in data explorer

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3875] opened 2018-07-11 16:48 UTC
to repro, open data explorer, select a field, then try to view as a Table.

`Uncaught (in promise) TypeError: Cannot read property 'results' of undefined`

![image](https://user-images.githubusercontent.com/4805997/42587387-6b6b3932-84ef-11e8-8cc0-180625c30216.png)

**Comment by 121watts** [comment] 2018-07-11 17:53
dupe of #3862

**Closed by 121watts** 2018-07-11 17:53 UTC
Labels: bug
