### ISSUE TITLE
RFC: User should be able to determine their Chronograf version number via the UI

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1624] opened 2017-06-17 01:33 UTC

**Comment by timraymond** [comment] 2017-06-19 15:32
Yes, absolutely this. Also, it should be possible to determine whether a new version is available from within Chronograf.

**Comment by timraymond** [comment] 2017-06-20 15:05
Dupe of #1532

**Comment by timraymond** [comment] 2017-06-29 18:04
@jaredscheib Can this be closed given #1662 ?

**Comment by jaredscheib** [comment] 2017-06-29 20:46
Yep!

**Closed** 2017-06-29 20:47 UTC
