### ISSUE TITLE
Add mock version organizations store that does proper vetting of org for tests

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2239] opened 2017-11-03 13:08 UTC
Our mocks store currently do not do any checking organization context logic. This is resulting in a bug (fixed in 6539e5eb) where a resource was being artificially restricted, even though the user should have had the access to see the resource.

**Comment by desa** [comment] 2017-11-03 16:57
Issue also came up 0d811e57a0c0435314d0d43a5c956a02cc764335

**Comment by desa** [comment] 2017-11-06 19:27
While not exactly the same, we've encountered a few other issues where the mock store ended up giving us the appearance that something was wrong, when in fact it was benign. See b7533c00. 

In this case, our test specified that our mock was not a super admin, but our test parameters had super admin set to be true. This resulted in the JSON we generated to contain `superAdmin: false` when it should have been `superAdmin: true`. This on the surface was concerning, but what this test was actually testing was that user making the request had the authorization to access the underlying store. So even though the end data that was returned was "wrong", the test was still behaving as expected.

I think that this issue should be changed to instead be an `Add integration suite to chronograf`.

**Comment by jaredscheib** [comment] 2017-11-06 19:54
Thoughts @goller?

**Comment by jaredscheib** [comment] 2017-11-27 21:55
Let's tackle the specific items named in here, but not create a mock organizations store, as part of the same PR addressing #2338.

**Comment by desa** [comment] 2017-12-06 00:24
TODO:

- [ ] Add Users tests
- [ ] Add Organizations tests
- [ ] Add Servers tests
- [ ] Add Layouts tests
- [ ] Add Sources tests
- [ ] Add Me tests
- [ ] Add Dashboards tests

**Comment by nhaugo** [comment] 2017-12-11 21:23
Dupe of #2487

**Closed by nhaugo** 2017-12-11 21:23 UTC
Labels: chore, multitenancy, ready
