### ISSUE TITLE
Add table as option for visualization type

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2246] opened 2017-11-03 19:12 UTC
Having context for the metrics being displayed can be incredibly useful for investigation or information. This visualization type would allow users to add a table to display contextual information along with their metrics.

Possible Use cases:
- User has a dashboard showing error counts in their logs, and suddenly there is a spike. User has been storing the actual log line text as a metric. There are two graphs on the dashboards: a line graph showing the count of errors, and a table showing the actual log lines. When the user hovers over the line graph, the table displays the appropriate log lines for that timeframe.
- User has a build dashboard displaying information about their CI system. When there are errors with the build, a user could see at a glance what the issue is or who broke the build by looking at the log line displayed in the table.
- User has a dashboard displaying tweets and hashtag metrics for their brand. They would also like to display the most recent 20 tweets from their users. They would use the table option with an order by and a limit.

We might consider requiring all table queries to have a limit by clause attached to them for performance reasons.

Other visualization tools have this capability as well:
- http://docs.grafana.org/features/panels/table_panel/
- https://www.elastic.co/guide/en/kibana/current/data-table.html#datatable-viewing-detailed-information

**Comment by nhaugo** [comment] 2017-11-03 19:59
Dupe of #1686

**Closed by nhaugo** 2017-11-03 19:59 UTC
Labels: design, feature request
