### ISSUE TITLE
Alert Builder: By default {{.ID}} seems to add a :nil to the end of it

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2685] opened 2018-01-08 23:58 UTC
When i'm trying to build my email template, and i use `{{.ID}}` in the subject line, it always appends a `:nil` to the end. I don't see a way around it other than going into the TICKscript and editing it by hand.

![screen shot 2018-01-08 at 3 56 14 pm](https://user-images.githubusercontent.com/4805997/34698383-ba88988c-f48c-11e7-9472-993b5e93a26c.png)

**Comment by goller** [comment] 2018-01-09 00:08
@russorat this is a duplicate of #2681 (and fixed by #2684)

**Closed by goller** 2018-01-09 00:08 UTC
Labels: bug, duplicate
