### ISSUE TITLE
Populate `Host List` from multiple databases

### ISSUE THREAD

**Issue by dgnorton** [influxdata/chronograf#2023] opened 2017-09-25 19:41 UTC
Currently, the `Host List` page is populated from a single database (telegraf is the default). It would be nice if multiple databases could be specified to pull hosts from.

E.g., if an operator has `telegraf` on some nodes configured to write to `db1` and configured to write to `db2` on other nodes, it should be possible to populate `Host List` from both databases.

Maybe the `Telegraf database` config option on the `Connection Details` dialog could accept either `*` to specify all databases or a comma separated list of database names. Or, possibly a regex.

**Comment by pstatho** [comment] 2017-09-25 19:55
Alternatively there could be a dropdown at the top to switch from one database to another (similar to Dashboard switch). When you switch to another database the Host List would display the hosts from the selected database.

**Comment by nhaugo** [comment] 2017-10-11 23:58
Closing as a dupe of #682

**Closed by nhaugo** 2017-10-11 23:58 UTC
Labels: feature request
