### ISSUE TITLE
[Feature request] add dropdown menu for switching sources

### ISSUE THREAD

**Issue by rlex** [influxdata/chronograf#689] opened 2016-12-13 23:40 UTC
It will be nice little feature to have dropdown menu, for example in top right corner for switching influxdb sources.
IE i have different databases for prod / staging / etc, so it will be good to have fast access to switching them.

**Comment by alexpaxton** [comment] 2016-12-14 00:00
@rlex is this something you would want in the Data Explorer? Or would you want it in the dashboards as well?

**Comment by rlex** [comment] 2016-12-14 11:30
Explorer already have indicator of current store, so making it selectable will do the trick.
Selector in dashboards will be nice too.
If i understood correctly, kapacitor browser (alerting -> kapacitor rules) uses user configured in kapacitor?

**Comment by fabiopedrosa** [comment] 2016-12-15 16:34
+1

**Comment by alexpaxton** [comment] 2016-12-15 19:48
@rlex What do you think about this?
![reset-kap-defaults](https://cloud.githubusercontent.com/assets/2433762/21239581/4be3060e-c2bc-11e6-9a78-94d2b5e51de4.gif)

You would still have to click `Connect` for the changes to save

**Comment by jademcgough** [comment] 2016-12-16 04:43
I think this is a dupe of #596

**Comment by nhaugo** [comment] 2016-12-20 17:51
Lets put this on a feature branch but not merge it right away

**Comment by nhaugo** [comment] 2017-01-04 01:38
@jademcgough Not a dupe of #596, this is for switching active influxdb sources.

**Comment by jackzampolin** [comment] 2017-01-09 23:59
+1000

**Comment by jademcgough** [comment] 2017-01-12 23:42
@nhaugo could we talk about the design for this. Could use some thought around the design (the source impacts most pages, should it be changeable everywhere?)

**Comment by pauldix** [comment] 2017-04-01 18:10
+1 for this. I just tried to click the source at the top right of the page to change and was thrown off when it didn't drop down like the date selector.

**Comment by russorat** [comment] 2018-12-03 22:57
closing due to lack of activity

**Closed by russorat** 2018-12-03 22:57 UTC
Labels: design, discussion, enhancement, need wireframes
