### ISSUE TITLE
Custom dashboard, set units for y axe

### ISSUE THREAD

**Issue by xandr2** [influxdata/chronograf#1536] opened 2017-05-24 09:57 UTC
I created a graph for interface statistic (in my custom dashboard), but it shows units like a numbers how I can change it to something like data rate `bits/sec`. 

![screen shot 2017-05-24 at 12 13 00 pm](https://cloud.githubusercontent.com/assets/14262685/26397843/46ac8bfa-4080-11e7-8d59-da9908aa35d8.png)

Also when I saw graphs in default dashboard view (Host list => check host) it shows different units on graphs and it looks good.

![screen shot 2017-05-24 at 12 41 48 pm](https://cloud.githubusercontent.com/assets/14262685/26397863/51f0763e-4080-11e7-9d5c-0572a1ada7ee.png)

I'm using Chronograf 1.3.0
I read docs but can't find a solution.

**Comment by goller** [comment] 2017-05-24 13:38
Hi, @xandr2 , our dashboards that ship with chronograf can have y-axis units, but, our custom dashboards do not support them yet.  

Here is a case that relates to adding them: https://github.com/influxdata/chronograf/issues/1413

Do you have ideas about what other kinds of settings you would like for the y-axis? Some have asked for control over precision and units.

**Comment by xandr2** [comment] 2017-05-24 14:56
Thank you for your answer, I will wait for new features) Also will be good if the y-axis can be labeled.   Like on an image:
![screen shot 2017-05-24 at 5 56 09 pm](https://cloud.githubusercontent.com/assets/14262685/26409835/5c3633ac-40aa-11e7-9f66-d60793070566.png)

**Comment by nhaugo** [comment] 2017-08-08 00:07
Dupe of #1339

**Closed by nhaugo** 2017-08-08 00:07 UTC
Labels: duplicate
