### ISSUE TITLE
Think through what needs to happen for `--new-sources` flag

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2475] opened 2017-12-04 21:24 UTC
https://github.com/influxdata/chronograf/blob/master/server/server.go#L53

Particularly, the addition of organizations.

**Comment by jaredscheib** [comment] 2017-12-04 21:49
We should double-check the other auth-related flags as well prior to 1.4.0.

cc @nhaugo

**Comment by nhaugo** [comment] 2017-12-04 23:27
@desa add the source to the default org

**Comment by jaredscheib** [comment] 2017-12-05 01:23
Sounds good. I've looked through the other server flags and don't see anything that seems to merit changes, like `--new-sources`.

Shall we put this under `Ready` @nhaugo?

**Comment by nhaugo** [comment] 2018-01-03 21:49
Dupe of #2659

**Closed by nhaugo** 2018-01-03 21:50 UTC
Labels: multitenancy, ready
