### ISSUE TITLE
Stacked graphs don't display properly along y-axis

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1766] opened 2017-07-23 00:22 UTC
Notice the clipping at the top of the y-axis when graph type is Stacked:
<img width="629" alt="screen shot 2017-07-22 at 5 16 04 pm" src="https://user-images.githubusercontent.com/6403018/28495464-4802c194-6f02-11e7-81f0-681f2b40d20f.png">

Whereas the same graph as a Line type:
<img width="604" alt="screen shot 2017-07-22 at 5 16 11 pm" src="https://user-images.githubusercontent.com/6403018/28495465-480a5c88-6f02-11e7-89d8-afd1f6a4d769.png">

**Comment by nhaugo** [comment] 2017-08-31 01:14
Pretty sure this is a dupe of https://github.com/influxdata/chronograf/issues/1460

**Closed by nhaugo** 2017-08-31 01:14 UTC
Labels: bug

**Comment by jaredscheib** [comment] 2017-08-31 01:16
Yep, good catch
