### ISSUE TITLE
 Chronograf (1.7.12) Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Waynedejager1** [influxdata/chronograf#5438] opened 2020-04-02 19:35 UTC
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
TypeError: Cannot read property 'name' of undefined
    at http://178.62.73.124/src.6549ea42.js:2350:385
    at Array.map (<anonymous>)
    at l (http://178.62.73.124/src.6549ea42.js:2350:310)
    at ca (http://178.62.73.124/src.6549ea42.js:716:59548)
    at fa (http://178.62.73.124/src.6549ea42.js:716:60685)
    at Wa (http://178.62.73.124/src.6549ea42.js:716:74893)
    at Va (http://178.62.73.124/src.6549ea42.js:716:75239)
    at wi (http://178.62.73.124/src.6549ea42.js:716:79907)
    at ki (http://178.62.73.124/src.6549ea42.js:716:79561)
    at Ha (http://178.62.73.124/src.6549ea42.js:716:78073)
```

**Comment by russorat** [comment] 2020-04-07 21:51
@Waynedejager1 thanks. could you fill in the following details?

What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

**Comment by sranka** [comment] 2021-04-12 09:55
duplicate of #5720

**Closed by sranka** 2021-04-12 09:55 UTC
