### ISSUE TITLE
Proxy requests in remote cluster instance failing

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2522] opened 2017-12-08 20:58 UTC
Immediately after #2521, as I just let the browser sit there, and a `SHOW DATABASES` query to proxy is issued, the following error results:
<img width="1006" alt="screen shot 2017-12-08 at 12 56 23 pm" src="https://user-images.githubusercontent.com/6403018/33784856-4d2acd42-dc17-11e7-8ac0-93213025a29c.png">
At a glance, it's pretty funky that `rp` has a value that includes what looks like tcp command line requests. Something to look at when diagnosing this bug.

**Comment by nhaugo** [comment] 2017-12-11 21:34
Dupe of #2527

**Closed by nhaugo** 2017-12-11 21:34 UTC
Labels: bug, multitenancy
