### ISSUE TITLE
Handle "partial": true

### ISSUE THREAD

**Issue by hasselrot** [influxdata/chronograf#1233] opened 2017-04-10 07:49 UTC
Hi!

Just noticed something when browsing back through the weekend graphs.

My dashboard is missing a lot of hosts when I choose "last 6 hours" or longer.
But it seems to work in the CLI and also the "pre-canned" system dashboard seems to work with older data.

If I edit the cell, it looks like this (only one host has any data):
![chronograf](https://cloud.githubusercontent.com/assets/16920380/24851097/bdaa06b8-1dd2-11e7-981b-d8bbd958ceee.png)

If I run the same query in the CLI (lots of data from many hosts):
![influxcli](https://cloud.githubusercontent.com/assets/16920380/24851124/d27a881a-1dd2-11e7-8c90-05392827f3a7.png)

**Comment by nhaugo** [comment] 2017-05-02 17:11
@hasselrot what version of chronograf and infuxd are you using.

**Comment by hasselrot** [comment] 2017-05-02 18:57
@nhaugo I have the same issue on Chronograf beta10. And influx is version 1.2.2.

Its clear now that the graph only shows the first host in the list, when I view more than 6 hours.

15minutes:
<img width="547" alt="screen shot 2017-05-02 at 20 53 33" src="https://cloud.githubusercontent.com/assets/16920380/25634134/cbed140a-2f79-11e7-9e9b-00b1db804d7d.png">

12hours:
<img width="553" alt="screen shot 2017-05-02 at 20 53 56" src="https://cloud.githubusercontent.com/assets/16920380/25634149/d2c7a3c6-2f79-11e7-888b-8d00a14056a2.png">

**Comment by 121watts** [comment] 2017-05-05 00:41
@hasselrot thanks for writing in!  I believe @lukevmorris and I found the crux of the biscuit as it were.  More info coming momentarily.

**Comment by lukevmorris** [comment] 2017-05-05 00:57
Heya @hasselrot! Thanks again for submitting this issue -- it was a fun one to track down. We tried reproducing this issue with a similar query:

```
SELECT "usage_user" FROM "telegraf"."autogen"."cpu" WHERE time > now() - 15m GROUP BY "host"
```

We ran this query at multiple time ranges, and it appears that we're truncating data somewhere between the Chronograf server and the InfluxDB client. We've found the following behavior:

1. Submitting the query via the InfluxDB CLI returns the full data set, with series for all hosts.
2. Submitting the query via the Chronograf UI with a narrow time range also returns the full data set, with series for all hosts.
3. Widening the time range from 15m to 1d returns series for 2 hosts, with the third one missing
4. Widening the time range from 1d to 2d returns only a single series, with two hosts missing.

Here's a dashboard that we hope illustrates the issue:
![screen shot 2017-05-04 at 5 33 20 pm](https://cloud.githubusercontent.com/assets/1438089/25730344/c802ef68-30f0-11e7-8569-88ed83155b7d.png)

The top three graphs have progressively widening time ranges, and you'll note that the third host (in green) is progressively truncated. Looking at each of these 
It might seem that the truncation would be due to there being no data present for host 3. However, as illustrated in the bottom right of the dashboard, host 3 has data throughout the widest (20h) time range.

We also suspected that we might be parsing the response incorrectly in certain cases. But as the time range increases, we definitely receive back fewer and fewer series.:

Over 15m, we see 3 series returned:
![screen shot 2017-05-04 at 5 36 59 pm](https://cloud.githubusercontent.com/assets/1438089/25730345/c8033914-30f0-11e7-88d6-cf846c873194.png)

Over 2d, we see 1 series returned:
![screen shot 2017-05-04 at 5 35 48 pm](https://cloud.githubusercontent.com/assets/1438089/25730346/c8040aa6-30f0-11e7-8685-cb8958d1ab36.png)

@goller any ideas?

**Comment by goller** [comment] 2017-05-05 13:59
@lukevmorris would you attach the server's debug logs to this issue?  I'd like to see if there are any differences in the query.

**Comment by goller** [comment] 2017-05-05 18:39
@hasselrot It looks like this is the `max-row-limit` issue that showed up in Influx 1.2

https://github.com/influxdata/influxdb/pull/8050
https://github.com/influxdata/influxdb/pull/8133
https://github.com/grafana/grafana/issues/7380

@rkuchan has docs here: 
https://docs.influxdata.com/enterprise/v1.2/troubleshooting/frequently_asked_questions/#why-are-my-grafana-panels-returning-truncated-partial-data

about how to fix it... the bottom line is to update the influxdb configuration like this:
```To prevent that issue, set max-row-limit to 0 to allow an unlimited number of returned rows.```

In the future we should support the `"partial": true` return or inform people that their data is truncated.  

I'm going to update the name of this issue to `Handle "partial": true` influx responses.

**Comment by nhaugo** [comment] 2017-08-30 22:33
I think this is resolved by @goller comment

**Closed by nhaugo** 2017-08-30 22:33 UTC
Labels: bug, ready
