### ISSUE TITLE
Ability to save query to dashboard from data explorer

### ISSUE THREAD

**Issue by markherring** [influxdata/chronograf#2029] opened 2017-09-26 21:00 UTC
Issue: In data explorer, it would be nice once you have explored the data and created the query, save or export it to a dashboard. Currently, you have to cut and paste.

**Comment by jaredscheib** [comment] 2017-09-26 21:43
Thanks, @markherring! We'll take a look into this.

**Comment by nhaugo** [comment] 2017-09-29 01:39
Dupe of #620

**Closed by nhaugo** 2017-09-29 01:39 UTC
Labels: feature request, User Experience
