### ISSUE TITLE
Support units per graph

### ISSUE THREAD

**Issue by PitPaul** [influxdata/chronograf#1413] opened 2017-05-08 18:43 UTC
chronograf_1.2.0~beta10_amd64.deb on Ubuntu 16.04
![chronograf-memory](https://cloud.githubusercontent.com/assets/26178409/25819507/776ef81c-342e-11e7-96f5-4fb03e4ab8d9.png)
On screen , lower y value is 500M then goes to Bytes.

**Comment by rizadh** [comment] 2017-05-11 14:10
Well, I believe the prefixes stand for 'million' and 'billion' respectively, so it's not truly a bug.

However an option to somehow use metric units (and their respective abbreviations) on the Y-axis would be quite nifty!

**Comment by PitPaul** [comment] 2017-05-11 14:42
Right, I realised that later  :-) ,  I'm thinking all my life in SI units.
BTW localisations is needed

**Comment by goller** [comment] 2017-05-11 16:18
@PitPaul thanks for writing in!  We'd like to allow units to be defined graph.  I'd like to reopen this with a new title, "Support units per graph"

**Comment by PitPaul** [comment] 2017-05-11 18:28
Well although this my be solution in that case, but I think we should make another approach . There are more of this units and names, time date specs, characters in national languages etc...
I think we could make this with language templates (look at this tool https://www.transifex.com/wildfire-games/0ad/)

**Comment by nhaugo** [comment] 2017-08-08 00:07
Dupe of #1339

**Closed by nhaugo** 2017-08-08 00:07 UTC
