### ISSUE TITLE
Dynamic Dashboard and Graph Names based on DB Content

### ISSUE THREAD

**Issue by davidgs** [influxdata/chronograf#2108] opened 2017-10-11 20:27 UTC
It would be nice to be able to add a ${{tag_name}} or ${{value}} variable to a dashboard name, or a Graph name such that it is dynamically updated in real time. 

Using a Tag would set the name without it changing. Using a Value, where the value is a String, would allow for the dashboard name to change based on incoming data. 

Use case: Monitoring live data from the National Hurricane Center. They provide an XML feed of live data/updates. One of the fields is if the storm is a "Hurricane" or a "Tropical Storm". Another is the Name of the storm. If I'm tracking this in InfluxDB, the name of the Dashboard should adjust to "Tropical Storm Foo" and, if it becomes a hurricane, "Hurricane Foo", etc.

**Comment by nhaugo** [comment] 2017-10-12 00:35
Dupe of #1973

**Closed by nhaugo** 2017-10-12 00:35 UTC
Labels: feature request
