### ISSUE TITLE
Chronograf 1.10.0 regression versus 1.9.4 when using BASE_PATH

### ISSUE THREAD

**Issue by R290** [influxdata/chronograf#6008] opened 2022-11-17 14:21 UTC
__Steps to reproduce:__

1. Configure Chronograf to use a base path by setting the following environment variable: `BASE_PATH=/chronograf`
2. Successfully load the landing page on 1.9.4
3. Upgrade to 1.10.0
4. Black page is shown

__Expected behavior:__

Successfully load Chronograf when using a base path

__Actual behavior:__

A black screen is shown on 1.10.0

__Environment info:__

* Chronograf version: 1.10.0
* Other relevant environment details: Firefox 102.3.0esr and Edge 107.0.1418.42 on Windows 10

__Config:__

 `BASE_PATH=/chronograf`

__Logs:__

Firefox log:
![image](https://user-images.githubusercontent.com/46033588/202470882-b70db184-d5b0-4478-ba19-36110044310d.png)

Edge log:
![image](https://user-images.githubusercontent.com/46033588/202470959-56c11439-35e0-4e07-8865-7cddf67ddd2f.png)

**Comment by R290** [comment] 2022-11-17 14:47
Just saw the changelog for v1.10.1. Can somebody tag this release and make it available on Docker Hub? Thanks!

**Comment by sranka** [comment] 2022-11-20 17:33
Duplicate of #6000

**Closed by sranka** 2022-11-20 17:33 UTC

**Comment by sranka** [comment] 2022-11-20 17:37
The fix is available in the nightly build, `docker pull quay.io/influxdb/chronograf:nightly`

**Comment by SaswatPadhi** [comment] 2022-11-21 04:27
The nightly image doesn't work on `arm64` :(

Any alternatives? Any estimates on when the patch is going to land on stable?
