### ISSUE TITLE
Y-axis should scale appropriately for a cell with stacked graph type and tag groupbys

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1091] opened 2017-03-28 00:59 UTC
When we group by a tag (e.g. `cpu` with 9 values)
And we select Stacked as the visualization type

It seems to stack the graphs higher than 100% (overflowing through the top of the graph)
<img width="1680" alt="screen shot 2017-03-27 at 5 55 37 pm" src="https://cloud.githubusercontent.com/assets/1438089/24384221/1a7ce94e-1317-11e7-9c68-1fcd2a8ca5fb.png">

**Comment by danigrmartinez** [comment] 2017-05-09 20:03
+1

I saw the same issue when doing the demo with telegraph:
`SELECT "memory_usage_bytes" FROM "telegraf"."autogen"."kubernetes_pod_container" WHERE time > :dashboardTime: GROUP BY "pod_name"`

<img width="1336" alt="screen shot 2017-05-09 at 2 55 53 pm" src="https://cloud.githubusercontent.com/assets/1847896/25870118/908a69a4-34c8-11e7-8a39-f187459b905f.png">

**Comment by danlg** [comment] 2017-06-13 20:55
same issue reported

**Comment by nhaugo** [comment] 2017-06-13 21:49
Dupe of https://github.com/influxdata/chronograf/issues/1460

**Closed by nhaugo** 2017-06-13 21:49 UTC
