### ISSUE TITLE
 Chronograf (1.7.6) o is not a function

### ISSUE THREAD

**Issue by denissduan** [influxdata/chronograf#5041] opened 2019-01-15 07:21 UTC
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
TypeError: o is not a function
    at d.<anonymous> (http://localhost:8888/src.5a8fa5bd.js:4691:3998)
    at pl (http://localhost:8888/src.5a8fa5bd.js:716:45572)
    at dl (http://localhost:8888/src.5a8fa5bd.js:716:45322)
    at xi (http://localhost:8888/src.5a8fa5bd.js:716:84392)
    at wi (http://localhost:8888/src.5a8fa5bd.js:716:79945)
    at ki (http://localhost:8888/src.5a8fa5bd.js:716:79561)
    at Le (http://localhost:8888/src.5a8fa5bd.js:716:90853)
    at We (http://localhost:8888/src.5a8fa5bd.js:716:10444)
    at Fn (http://localhost:8888/src.5a8fa5bd.js:716:30800)
    at Si (http://localhost:8888/src.5a8fa5bd.js:716:85578)
```

**Comment by russorat** [comment] 2019-01-15 23:30
@denissduan thanks for reporting. could you provide a screenshot of what you are seeing? we are unable to reproduce this.

**Comment by russorat** [comment] 2019-01-23 16:51
Closing for now. If you are stiff facing issues, please reopen with additional details.

**Closed by russorat** 2019-01-23 16:51 UTC
