### ISSUE TITLE
Query builder UI elements stop working after hand-editing Query

### ISSUE THREAD

**Issue by davidgs** [influxdata/chronograf#2186] opened 2017-10-31 19:57 UTC
![safariscreensnapz013](https://user-images.githubusercontent.com/2071898/32245992-f826dc54-be53-11e7-8b69-0d06744ae037.png)

If you make any hand-edits to a query in the query builder, after that, none of the UI elements have any effect on the query.

**Comment by nhaugo** [comment] 2017-11-02 20:51
Dupe of #2161

**Closed by nhaugo** 2017-11-02 20:51 UTC
