### ISSUE TITLE
Kapacitor Rule Config Multi-Select Alert Outputs

### ISSUE THREAD

**Issue by cryptoquick** [influxdata/chronograf#863] opened 2017-02-10 04:51 UTC
Currently, only one alert output can be selected for a rule... It might be prudent to add a checklist next to any enabled alert output in the "Send this alert to" dropdown, and a check box next to the input field to enable/disable that output. The API currently supports multiple alert outputs on a rule, so the UI should as well.

In addition, only one alert can be configured at a time for a rule. The interface simply doesn't have a pattern for editing multiple alerts for a rule without saving them separately, one at a time.

We may also wish to gray out services we provide but haven't yet been configured in the global alert config.

<img width="436" alt="screenshot 2017-02-09 21 48 58" src="https://cloud.githubusercontent.com/assets/285690/22814542/ac4df978-ef11-11e6-8ce9-18e62da14aa0.png">

**Comment by ebb-tide** [comment] 2017-12-19 22:02
dupe of #1736

**Closed by ebb-tide** 2017-12-19 22:02 UTC
Labels: design, enhancement, kapacitor
