### ISSUE TITLE
Chronograf log viewer: Time selection is fairly broken.

### ISSUE THREAD

**Issue by jherman4** [influxdata/chronograf#5608] opened 2020-11-06 01:41 UTC
If I select a timestamp on the histogram it starts loading events hours after that that timestamp and as it loads new data it seems to refresh the log list and takes the cursor to the top of the list everytime it does so. As a result it is extraordinarily difficult to see the log messages I want to view. This tool has so much potential, quality lightweight graphical log parsers can be difficult to find. However this defect makes it pretty hard to use.

 If you want clarification I would be happy to provide a screen capture of the issue in action as it is 100% reproducible. I'm not going to waste my time doing that unless I get a response on here as the last legitimate issue with the TICK stack that I raised here was eventually automatically closed for lack of any response.

**Comment by timhallinflux** [comment] 2020-11-20 01:30
Thanks @jherman4.  We'll have a look.  As for your other issue, that was for a client library which was community supported.  We've taken over responsibility for the client libraries for InfluxDB v2 so that we can ensure more consistency in the various implementations and ensure that issues are appropriately addressed.

**Comment by ivankudibal** [comment] 2020-11-20 09:23
Hello @jherman4 it'd be great to share the screencast with us as attachment to this issue if you do not mind. Thank you

**Comment by sranka** [comment] 2020-12-22 11:10
> If I select a timestamp on the histogram it starts loading events hours after that that timestamp 

This is already fixed by #5649 ... it tries to load at most for the last 5 minutes.
> as it loads new data it seems to refresh the log list and takes the cursor to the top of the list everytime it does so.

I cannot reproduce this. The data are refreshed only if `now` is the timestamp and the vertical scrollbar is at the top ... it is expected to happen then. 

Please feel free to reopen it with more details, including chronograf and browser version.

**Closed by sranka** 2020-12-22 11:10 UTC
Labels: area/log viewer, pm/consumability, usability
