### ISSUE TITLE
Request: Switch Hosts from Host view via search suggestions

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#167] opened 2016-10-03 23:44 UTC
Currently the user would have to click back in the browser, or click the host list link in the sidenav to return to the hosts list page. There is no way to switch between hosts without returning to the host list.

This flow proposes a solution to the problem:
![sketch-host-switch](https://cloud.githubusercontent.com/assets/2433762/19057904/2ee5d1a2-8988-11e6-90a3-91feb55f0a7b.jpg)

Goals of design:
- Use as little real estate as possible
- Not technically a dropdown
- No back buttons (to be consistent with the rest of the UI)
- Filtering through a long list (500+) should be effortless and intuitive

**Comment by timraymond** [comment] 2017-01-13 14:54
@nhaugo I missed this when I picked this card up, but this kind of feels like a dupe of #596... is it?

**Comment by nhaugo** [comment] 2017-01-13 18:29
You are correct, its a dupe. I am moving it to done.

**Closed** 2017-01-13 18:29 UTC
Labels: enhancement, in progress
