### ISSUE TITLE
Ability to select multiple items from template variables

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2244] opened 2017-11-03 17:38 UTC
It would be really nice to be able to select multiple items from the drop-down list for Template Variables and for Chronograf to be smart enough to update the query. If using checkboxes, there should be a select all and deselect all option as well. This would be useful for users selecting multiple hosts or multiple key values to display on the same chart.

- Full details of your operating system (or distribution) e.g. 64-bit Ubuntu 14.04.
 - Mac OS X 10.13 Chrome Version 63.0.3239.18
- The version of Chronograf you are running
 - 1.3.8-3
- Whether you installed it using a pre-built package, or built it from source.
 - Installed
- A small test case, if applicable, that demonstrates the issues.
- A screenshot, when appropriate, to demonstrate any issues that are related to the UI

![image](https://user-images.githubusercontent.com/4805997/32387429-ae8357b4-c081-11e7-809b-aba0876ef51e.png)

**Comment by jaredscheib** [comment] 2017-11-03 19:02
Thanks @russorat!

What do you imagine such a query would look like?

We do have a MultiSelectDropdown component in some other parts of the app that could probably be used in this case with some slight style adjustments.

**Comment by nhaugo** [comment] 2017-11-03 20:00
Dupe of #1313

**Closed by nhaugo** 2017-11-03 20:00 UTC
Labels: feature request
