### ISSUE TITLE
Submitting two 'time' conditionals in WHERE incorrectly coerced into one conditional on submit

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1718] opened 2017-07-13 02:00 UTC
![wheretime](https://user-images.githubusercontent.com/6403018/28180135-157fc082-67b9-11e7-8fd4-f8a0f920de1b.gif)

**Comment by cryptoquick** [comment] 2017-07-14 00:09
to triage that I would check out a branch prior to custom time range being merged in, to see if that's a regression, or just normal behavior. it might be a recent regression with the customtimerange stuff

**Comment by russorat** [comment] 2018-12-19 00:30
closing due to inactivity

**Closed by russorat** 2018-12-19 00:30 UTC
Labels: bug
