### ISSUE TITLE
Add an option to allow self-signed certificates to be accepted for OAuth servers

### ISSUE THREAD

**Issue by saibotk** [influxdata/chronograf#5491] opened 2020-05-22 02:21 UTC
As the title says, I think it would be useful to have an option to explicitly allow self-signed certificates for and OAuth server.

The reasoning behind this, is that setting up Chronograf and the TICK stack to monitor local / private infrastructure is for sure not an uncommon task.

I wanted to protect Chronograf with authorization, so I had to also deploy a Keycloak server, to handle the OAuth side and configure Chronograf to use it, but since all services are in my local network with their self-signed certificates, Chronograf reported an error when trying to login: "x509: certificate signed by unknown authority". 

I think it would be awesome to allow people to use a private SSO or OAuth service, whether to explore stuff or actually use it with the TICK stack to monitor their infrastructure.

Let me know what you think, or if this would be possible to implement. 

:+1: for the great work so far!

**Comment by glinton** [comment] 2020-06-11 17:17
Have you tried with the nightly build or latest chronograf 1.8.x? I believe this should be possible with the changes in https://github.com/influxdata/chronograf/pull/5461

Specifically there are two added flags that allow you to either ignore the cert, or pass in the ca cert that signed the cert.
https://github.com/influxdata/chronograf/blob/ad9c6b2e0b822bb34461e35fac2b27aa80ce4180/server/server.go#L105-L106

I'm going to close this as afaik it's resolved (and duplicate of https://github.com/influxdata/chronograf/issues/5402) but feel free to re-open if those later builds don't provide the functionality you were looking for.

**Closed by glinton** 2020-06-11 17:17 UTC
