### ISSUE TITLE
Data Explorer fails in Google Chrome

### ISSUE THREAD

**Issue by hoomanv** [influxdata/chronograf#1810] opened 2017-08-01 07:29 UTC
Chronograph version: 1.3.5.0 (64-bit)
Google Chrome version: 60.0.3112.78 (64-bit)
Windows version: 10

Opening Data Explorer in Chrome fails with error: Unable to connect to Chronograph server.
But it works fine in Microsoft Edge.

**Comment by jaredscheib** [comment] 2017-08-01 17:57
Thanks for reporting this, @hoomanv.

Was this after an upgrade? Or this a new installation of Chronograf?

If it's post-upgrade, was it working previously? If it doesn't seem like an upgrade is at fault, do you recall any particular actions you may have made in Chronograf after which it seemed to stop working.

It's difficult to guess specifically what the issue is since this is very general, but the likely culprit is localStorage, for which the best solution is to call `localStorage.setItem('state', null)` in your developer console. You will lose queries you've built in Data Explorer, but let me know if this helps you out and gets Chrome working again.

**Comment by hoomanv** [comment] 2017-08-02 08:05
That was my first experience with chronograph. Everything worked fine in Chrome for about an hour until suddenly it broke. I don't remember the exact course of actions I took. BTW deleting the localStorage fixed it. For your reference, the "state" value that caused the issue was:

`{"app":{"persisted":{"autoRefresh":0,"showTemplateControlBar":false}},"dataExplorerQueryConfigs":{"5469729e-39f9-457d-853b-c264827691c1":{"status":{"error":"TypeError: Cannot read property 'some' of undefined"}}},"timeRange":{"upper":"2017-07-31T11:17:00.000Z","lower":"2017-04-01T11:17:00.000Z","defaultGroupBy":"10s","seconds":300,"inputValue":"Past 5 minutes","menuOption":"Past 5 minutes"},"dataExplorer":{"queryIDs":[]},"VERSION":"1.3.5-0"}`

**Comment by sebastianarena** [comment] 2017-08-21 16:30
+1

I installed Chronograf a little bit over 2 days ago and it worked fine.
After messing around a couple of days, now it seems I can no longer enter that section.

It might be related to #1772 , as I did testing for a few hours with kapacitor rules, and there might me a lot of unnecessary queries loaded there.

**Comment by jaredscheib** [comment] 2017-08-21 18:15
This appears to be related to how `fetchTimeSeriesAsync` in`ui/src/shared/actions/timeSeries.js` is invoking `handleError` to set the status upon an error, and instead of it setting an error about a time series result, it's setting an error about a JavaScript problem. We'll try to investigate. But in the meantime, do you happen to know what query may have caused this corruption?

If you call `localStorage.setItem('state', null)` in your Chrome Developer console, it should clear this problem for now.

**Comment by sebastianarena** [comment] 2017-08-21 23:13
@jaredscheib confirmed the temp fix worked perfectly in Chrome

**Comment by russorat** [comment] 2018-06-22 16:09
closing since i don't think we've seen this in a while.

**Closed by russorat** 2018-06-22 16:09 UTC
