### ISSUE TITLE
Gauge component won’t accept negative numbers

### ISSUE THREAD

**Issue by davidgs** [influxdata/chronograf#2764] opened 2018-02-06 19:40 UTC
![gauge-fail](https://user-images.githubusercontent.com/2071898/35881495-f80d3ac2-0b4e-11e8-92a4-1fb737af8693.gif)
The scale setting for the gauge component won’t accept negative numbers. Some measurement data contains negative numbers — RSSI data is almost exclusively negative — but attempts to enter a negative number fail. 

Steps to reproduce:

1) create a gauge component
2) attempt to set minimum scale to a negative value.

**Comment by russorat** [comment] 2018-02-07 19:45
@davidgs i can't reproduce in the latest build. closing for now, but please reopen if after upgrading to the latest, you still see this.

**Closed by russorat** 2018-02-07 19:45 UTC
Labels: bug, ready

**Comment by nhaugo** [comment] 2018-02-07 19:58
I tested master on chrome and safari and could not recreate either

**Comment by davidgs** [comment] 2018-02-08 15:16
I'm running latest Chronograf: 
Davids-MacBook-Pro:telegraf davidgs$ brew install chronograf
Warning: chronograf 1.4.0.1 is already installed

And I cannot use a negative scale setting. 

I can set negative scale values for Bar Graphs and all other components but NOT for a gauge. 
![gauge2](https://user-images.githubusercontent.com/2071898/35980582-12e48ab0-0cb9-11e8-9ead-0f9d1e670810.gif)

**Comment by russorat** [comment] 2018-02-08 17:26
@davidgs thanks for following up. looks like it was fixed in this commit: https://github.com/influxdata/chronograf/commit/72d2f7986a9672ee36152e3732d977cebf24b390 

the strange thing is that it was tagged for 1.4.0.1 so it should be in the last release. @nhaugo and I have both confirmed that it is fixed in master though.
