### ISSUE TITLE
Ability to set default node

### ISSUE THREAD

**Issue by danisabad** [influxdata/chronograf#1236] opened 2017-04-10 14:41 UTC
Hello.

I believe there should be ability to set 'Default Node' via web-interface, because there is a lot of cases when you can't handle data without it, as I understand.

@nathanielc was quite straitforward [here](https://github.com/influxdata/kapacitor/issues/616):
- Am I forced to use default node?
- At the moment yes

**Comment by nhaugo** [comment] 2017-09-05 18:20
Dupe of #1368

**Closed by nhaugo** 2017-09-05 18:20 UTC
Labels: discussion
