### ISSUE TITLE
As a user, I can reorder the template variables in my TVarControlBar

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1623] opened 2017-06-17 00:02 UTC
New template variables are added to the front of the list

<img width="1595" alt="screen shot 2017-06-16 at 5 03 15 pm" src="https://user-images.githubusercontent.com/1438089/27248246-b57a2c12-52b5-11e7-9d3e-9ef017f298cc.png">

If I have a long list of template variables, I may want to add a tvar, and then move the new tvar to the middle of the list. Click + drag?

**Comment by jaredscheib** [comment] 2017-08-23 16:53
Dupe of #1466

**Closed by jaredscheib** 2017-08-23 16:53 UTC
