### ISSUE TITLE
If Kapacitor is not configured, Alerts --> Create says 'Loading Rules...' indefinitely

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2504] opened 2017-12-07 03:22 UTC
<img width="1440" alt="screen shot 2017-12-06 at 7 21 41 pm" src="https://user-images.githubusercontent.com/6403018/33697227-c8e5e0b0-daba-11e7-99ee-81d46b702ea6.png">

**Comment by goller** [comment] 2017-12-10 16:52
This is a duplicate of #2458

**Closed by goller** 2017-12-10 16:52 UTC
Labels: bug, duplicate, polish
