### ISSUE TITLE
Add percentile field function

### ISSUE THREAD

**Issue by negbie** [influxdata/chronograf#1961] opened 2017-09-04 09:43 UTC
I hope i don't overlook it but right now I see following field functions in the GUI:
mean, median, count, min, max, sum, first, last, spread, stddev. The most important for my coworkers 'percentile' seems to be missing.

Sure I can easily add SELECT percentile("value", 95) AS "percentile_value" FROM... in the query field but it would be nice to simply select it from the function list.

**Comment by nhaugo** [comment] 2017-09-05 20:12
@negbie this is a dupe of #663, if you thumbs up that issue it will help us prioritize.

Thanks

**Closed by nhaugo** 2017-09-05 20:12 UTC
