### ISSUE TITLE
 Chronograf (1.7.0) Cannot read property 'dataType' of undefined

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4857] opened 2018-11-29 22:29 UTC
I was trying to run the following query:

```
from(bucket: "metrics/autogen")
  |> range(start: 0)
  |> filter(fn: (r) => r._measurement == "response_time")
  |> group(by: ["server","container","_time"])
  |> drop(columns: ["_measurement"])
  |> max()
```

```TypeError: Cannot read property 'dataType' of undefined
    at E.t.lineGraph (http://localhost:8888/russ//src.51be23b2.js:3296:3676)
    at Object.children (http://localhost:8888/russ//src.51be23b2.js:3296:6070)
    at w.value (http://localhost:8888/russ//src.51be23b2.js:3266:6471)
    at ia (http://localhost:8888/russ//src.51be23b2.js:716:58760)
    at aa (http://localhost:8888/russ//src.51be23b2.js:716:58602)
    at fa (http://localhost:8888/russ//src.51be23b2.js:716:60859)
    at Wa (http://localhost:8888/russ//src.51be23b2.js:716:74893)
    at Va (http://localhost:8888/russ//src.51be23b2.js:716:75239)
    at wi (http://localhost:8888/russ//src.51be23b2.js:716:79907)
    at ki (http://localhost:8888/russ//src.51be23b2.js:716:79561)```


![image](https://user-images.githubusercontent.com/4805997/49256229-29403680-f3e3-11e8-9747-11de71e032ae.png)


with the following data:
```
# DDL
CREATE DATABASE metrics

# DML
# CONTEXT-DATABASE: metrics

response_time,endpoint=/services/one,server=one,container=one response_time=0.1 1542661200000000000
response_time,endpoint=/services/two,server=one,container=one response_time=0.5 1542661260000000000
response_time,endpoint=/users,server=one,container=one response_time=0.3 1542661300000000000
response_time,endpoint=/services/one,server=one,container=two response_time=0.9 1542661200000000000
response_time,endpoint=/services/two,server=one,container=two response_time=2 1542661260000000000
response_time,endpoint=/users,server=one,container=two response_time=10 1542661300000000000
response_time,endpoint=/services/one,server=one,container=three response_time=0.1 1542661200000000000
response_time,endpoint=/services/two,server=one,container=three response_time=0.4 1542661260000000000
response_time,endpoint=/users,server=one,container=three response_time=0.1 1542661300000000000
response_time,endpoint=/services/one,server=one,container=four response_time=0.3 1542661200000000000
response_time,endpoint=/services/two,server=one,container=four response_time=0.8 1542661260000000000
response_time,endpoint=/users,server=one,container=four response_time=15 1542661300000000000
response_time,endpoint=/services/one,server=two,container=one response_time=0.4 1542661200000000000
response_time,endpoint=/services/two,server=two,container=one response_time=5 1542661260000000000
response_time,endpoint=/users,server=two,container=one response_time=0.2 1542661300000000000
response_time,endpoint=/services/one,server=two,container=two response_time=1 1542661200000000000
response_time,endpoint=/services/two,server=two,container=two response_time=3.4 1542661260000000000
response_time,endpoint=/users,server=two,container=two response_time=0.1 1542661300000000000
response_time,endpoint=/services/one,server=two,container=three response_time=4 1542661200000000000
response_time,endpoint=/services/two,server=two,container=three response_time=6 1542661260000000000
response_time,endpoint=/users,server=two,container=three response_time=0.1 1542661300000000000
response_time,endpoint=/services/one,server=two,container=four response_time=2.3 1542661200000000000
response_time,endpoint=/services/two,server=two,container=four response_time=11 1542661260000000000
response_time,endpoint=/users,server=two,container=four response_time=0.9 1542661300000000000
response_time,endpoint=/users,server=two,container=four response_time=0.9 1542661300000000000
```

**Comment by ischolten** [comment] 2018-11-30 01:12
dupe of https://github.com/influxdata/chronograf/issues/4831
should be fixed by https://github.com/influxdata/chronograf/pull/4846

**Closed by ischolten** 2018-11-30 01:12 UTC
Labels: bug
