### ISSUE TITLE
Issues with plotting graphs on explorer and Dashboard 

### ISSUE THREAD

**Issue by suntracks** [influxdata/chronograf#2688] opened 2018-01-09 10:45 UTC
I am using pandas to insert bulk data from csv to influxdb. Successfully managed to have the data in the db.
I am neither able to preview graphs from chronograf explorer option nor  insert graphs in the dashboard. This is the warning i get:

Your query is syntactically correct but returned no results

Current versions used:
influxdb version - 1.3.7
chronograf version - 1.3.3

code sample used

```
def upload_to_influx(file):

       data=[]
       new_data=[]
       data=pd.read_csv(file,header=None)
       new_data=data
       new_data.columns=[ 'User','Session', 'Desc','Timestamp','Value']
       ourdates = (pd.to_datetime(new_data['Timestamp'], format='%Y-%m-%d %H:%M:%S')

       new_data.index=ourdates
       client=init_influx()
       status = client.write_points(dataframe=new_data,measurement='param1',
                   tag_columns=[ 'User','Session', 'Timestamp','Desc',])
       return status
```
Would like to know if am missing something in the steps above? Any help is appreciated.

**Comment by goller** [comment] 2018-01-09 17:39
@suntracks is this a duplicate of #2482?

**Closed** 2018-01-09 18:27 UTC
Labels: duplicate
