### ISSUE TITLE
 Chronograf (1.8.0) Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by dbarohit** [influxdata/chronograf#5719] opened 2021-04-07 06:34 UTC
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
TypeError: Cannot read property 'name' of undefined
    at https://metrics.volvocars.net/src.5692061f.js:4911:4187
    at Array.map (<anonymous>)
    at d.get (https://metrics.volvocars.net/src.5692061f.js:4911:4112)
    at d.value (https://metrics.volvocars.net/src.5692061f.js:4911:2697)
    at d.value (https://metrics.volvocars.net/src.5692061f.js:1913:2204)
    at Ba (https://metrics.volvocars.net/src.5692061f.js:717:65834)
    at ja (https://metrics.volvocars.net/src.5692061f.js:717:65629)
    at $a (https://metrics.volvocars.net/src.5692061f.js:717:69008)
    at oo (https://metrics.volvocars.net/src.5692061f.js:717:91055)
    at uo (https://metrics.volvocars.net/src.5692061f.js:717:91442)
```

**Comment by sranka** [comment] 2021-04-12 05:24
A duplicate of #5720

**Closed by sranka** 2021-04-12 05:24 UTC
