### ISSUE TITLE
Mark Decommissioned Nodes

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/chronograf#1592] opened 2017-06-05 22:50 UTC
In cloud environments nodes can quickly come and go. Users should have an easy way to `decommission` nodes that are no longer in use. For example, if you scale to handle increased traffic and then scale back down to baseline there will be a number of "dead" nodes in the Host View. 

Deleting this data in the database is expensive (`DROP SERIES WHERE host = foo`) and not desirable (you might want that data for capacity planning) but not displaying the data on the front end is potentially easier. See this [community post](https://community.influxdata.com/t/mark-decommissioned-nodes-as-not-in-service/1179).

**Comment by nhaugo** [comment] 2017-08-30 22:32
Dupe of #1241

**Closed by nhaugo** 2017-08-30 22:32 UTC
Labels: feature request
