### ISSUE TITLE
Set warning level alerts

### ISSUE THREAD

**Issue by hasselrot** [influxdata/chronograf#1483] opened 2017-05-15 20:33 UTC
Would be great to be able to create warning alerts in Kapacitor from Chronograf.

**Comment by jademcgough** [comment] 2017-05-15 21:57
I completely agree. There's another request for this, but it hasn't been prioritized yet (see #669).

**Comment by nhaugo** [comment] 2017-05-16 22:14
Dupe of #669

**Closed by nhaugo** 2017-05-16 22:14 UTC
