### ISSUE TITLE
Graph y-axis scale is not correct when value is constant

### ISSUE THREAD

**Issue by danielnelson** [influxdata/chronograf#1900] opened 2017-08-18 02:47 UTC
I have a graph where the value has remained constant for ~1 day, when viewing only the period where the time has remained constant, there is no y-axis label and the graph appears flat at the bottom of the viewing area.  I have the min y-axis value set to 0.

2017/08/18 02:34:47 Chronograf 1.3.6.1 (git: 07fade83a6360429cfd9d52bbce9cd59cdd42399)

In this image, the graph is flat even though the value is 3.4K, and there is no y-axis on the graph:
![01](https://user-images.githubusercontent.com/1048079/29442140-99561af0-8384-11e7-982d-7898f1e10c48.png)

If I view a larger time period during which the value has changed the graph is correct:
![02](https://user-images.githubusercontent.com/1048079/29442147-a1640fea-8384-11e7-8b84-0b9df42896ce.png)

**Comment by core-process** [comment] 2017-08-19 13:02
Seems to be related to #1857

**Comment by core-process** [comment] 2017-08-19 13:07
Here is more info to reproduce the issue: https://github.com/influxdata/chronograf/issues/1857#issuecomment-323521048

**Comment by core-process** [comment] 2017-08-19 13:29
Here you will find a prepared VM to reproduce the issue: https://github.com/influxdata/chronograf/issues/1857#issuecomment-323523179

**Comment by 121watts** [comment] 2017-08-23 17:16
dupe of  #1857

**Closed** 2017-08-30 21:04 UTC
Labels: bug
