### ISSUE TITLE
Users should be able to convert an OSS into an enterprise source

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1021] opened 2017-03-14 20:26 UTC
When users go to the to the edit a source page, e.g. http://localhost:8888/sources/6/manage-sources/9/edit

Chronograf should check and see if that source is an enterprise source and show the proper UI elements if it can be upgraded

**Comment by 121watts** [comment] 2017-04-26 13:43
@nhaugo I would test this myself but all the enterprise clusters we were using for development were taken down.

**Comment by 121watts** [comment] 2017-04-26 15:31
@nhaugo with no way of detecting the meta service, an 'automatic' upgrade like this in chronograf is pretty :smile_poop:

If they are automatically upgraded from OSS to Enterprise by Chronograf, they will get into this odd quasi-enterprise state.  Without the metaUrl admin features are crippled.

This really brings up a larger issue.  If a meta node is not exposed to the Chronograf server, Chronograf really doesn't work with Enterprise.

**Comment by jademcgough** [comment] 2017-05-08 16:52
I'm fairly sure this is a dupe of a issue I resolved like a month or so ago.

**Comment by jademcgough** [comment] 2017-05-08 16:56
@nhaugo right now we check to see if the 'type' of the source, and show the metaURL in the form if it's an enterprise source. Not sure what else needs to be done for this, or if this is just an old story.

**Closed** 2017-05-08 18:57 UTC
