### ISSUE TITLE
Refactor remaining AJAX requests & error handling

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1301] opened 2017-04-15 00:53 UTC
https://github.com/influxdata/chronograf/pull/1265 resolves some of this, but there are many instances of unhandled errors in the app, especially those that use Promise syntax and don't have a `.catch`. These are revealed in the console when auth expires and there are outstanding AJAX requests that fail.

It would be good to do the following chores:
- [ ] handle multiple error notifications and/or suppress failure notifications on auth expiration
  - [ ] could include moving `publishNotifications` out of actions and pass message to `errorThrown()` action
- [ ] refactor AJAX requests called directly from components to use action creators & redux
- [ ] refactor AJAX that follows Promise pattern to `async/await` and catch and handle errors

**Comment by nhaugo** [comment] 2017-09-05 17:57
Dupe of #1539

**Closed by nhaugo** 2017-09-05 17:57 UTC
