### ISSUE TITLE
 Chronograf (1.7.10) Expected number or array but got string: 2285.4460001.

### ISSUE THREAD

**Issue by maneagle-dev** [influxdata/chronograf#5206] opened 2019-06-13 21:18 UTC
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
Error: Expected number or array but got string: 2285.4460001.
   at j (http://slave2:8888/src.6c53cef1.js:3158:1892)
   at W.prototype.parseArray_ (http://slave2:8888/src.6c53cef1.js:3158:31908)
   at W.prototype.start_ (http://slave2:8888/src.6c53cef1.js:3158:35555)
   at W.prototype.updateOptions (http://slave2:8888/src.6c53cef1.js:3158:36410)
   at value (http://slave2:8888/src.6c53cef1.js:3218:4872)
   at xi (http://slave2:8888/src.6c53cef1.js:716:84201)
   at wi (http://slave2:8888/src.6c53cef1.js:716:79918)
   at ki (http://slave2:8888/src.6c53cef1.js:716:79561)
   at Ha (http://slave2:8888/src.6c53cef1.js:716:77755)
   at Rl.enqueueSetState (http://slave2:8888/src.6c53cef1.js:716:47018)
```

**Comment by timhallinflux** [comment] 2019-06-26 07:47
Duplicate of https://github.com/influxdata/chronograf/issues/5207

**Closed by timhallinflux** 2019-06-26 07:47 UTC
Labels: duplicate
