### ISSUE TITLE
Alert Rule Builder: Save Alert Rule returns user to Status/Home page (regression?) and not to Alert rules list

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#2758] opened 2018-02-06 09:20 UTC
I reported this last week as issue #2740 however it was closed, because the fix to issue #2674 was expected to fix this issue as well.  It appears that the fix to #2674 has been merged.  I see in the edit TICKscript view the buttons Save New TICKscript and Exit, however when working with Alert Rule Builder the "Save Rule" button still returns me to the Status page. Apparently I failed to mention that the Save Rule button was clicked from "Alert Rule Builder" and not "TICKscript Editor"

Testing against (nightly build):
$ chronograf --version
2018/02/06 10:04:42 Chronograf 1.2.0~n201802050832 (git: 058df60e0e96ace38ea79808302a210a78bd3f2e)

Browser is Chrome 63
OS is Ubuntu 16.04

When working with Alert Rule Builder...

After clicking the "Save Rule" button on the Create new alert form, the Status/Home page loads.

I was expecting to be returned to the list of Alert Rules located through the Alerting/Create Icon.

I'm currently reviving Chronium Selenium tests, and from the story/test code it appears that returning directly to the rules list was the way it behaved previously.

![savealertrule01](https://user-images.githubusercontent.com/25881301/35851139-54603086-0b27-11e8-92a3-95210c7cee0d.png)

![savealertrule02](https://user-images.githubusercontent.com/25881301/35851152-61d0eff8-0b27-11e8-9489-00ad3750b2e1.png)

![savealertrule03](https://user-images.githubusercontent.com/25881301/35851174-77295566-0b27-11e8-966c-7ee9389f8a43.png)

**Comment by russorat** [comment] 2018-02-06 16:18
Thanks for reporting! i agree this should be changed.
- [ ] after saving a rule, return the user to the alert list page, not the status page.

**Comment by nhaugo** [comment] 2018-02-06 22:28
Fixed by https://github.com/influxdata/chronograf/issues/2674

**Comment by ebb-tide** [comment] 2018-02-07 19:44
Noticed additional quick to fix bug: users not routed to correct config panel when saving/updating rule. (only when exiting without saving)
- [ ] route user to correct config panel in config page when saving and updating

**Comment by russorat** [comment] 2018-02-09 01:05
@ebb-tide i'm getting redirected back to /status every time i refresh any page. not sure if this is the cause

**Closed** 2018-02-09 18:57 UTC
Labels: bug, in progress
