### ISSUE TITLE
Associate a default Time Range with a dashboard

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#1980] opened 2017-09-08 10:30 UTC
Currently Time Ranges do not appear to be associated with Dashboards. Specifically, when a dashboard is loaded  for the first time in Chronograf, Chronograf applies the `Last Hour` time range.

While this is a sensible default for continuous, present, data, it can be clunky for historical data. When dealing with historical data, the user is forced to select either an absolute Time Range, or if their data is not too far in the past, an alternative relative Time Range.

It would be nice if it was possible to associate a default Time Range with a dashboard. Then, whenever the dashboard was loaded up the default Time Range was applied.

**Comment by nhaugo** [comment] 2017-10-12 00:32
Dupe of #2038 will be fixed in 1.3.11.0

**Closed by nhaugo** 2017-10-12 00:32 UTC
Labels: feature request
