### ISSUE TITLE
Kapacitor Alerts section missing a few supported services

### ISSUE THREAD

**Issue by nathanielc** [influxdata/chronograf#320] opened 2016-11-02 21:02 UTC
Chronograf is missing a few alerting systems that Kapacitor supports:

- [ ] OpsGenie
- [ ] Talk
- [ ] Alerta

**Comment by nhaugo** [comment] 2017-01-05 20:03
Dupe of #625 #737 and #738

**Closed by nhaugo** 2017-01-05 20:03 UTC
