### ISSUE TITLE
Unclear what the address should be when connecting to a new source

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#2090] opened 2017-10-09 16:50 UTC
I forgot to write http:// 

Previously, there was an example.  

![image](https://user-images.githubusercontent.com/1922921/31349233-062db2fa-ace8-11e7-9a0b-1a9f3578303f.png)

**Comment by nhaugo** [comment] 2017-10-09 16:59
Closing as dupe of #1497

**Closed by nhaugo** 2017-10-09 16:59 UTC
Labels: User Experience
