### ISSUE TITLE
"Loading Rules..." appears and doesn't go away (when no Kapacitor connection)

### ISSUE THREAD

**Issue by stevebang** [influxdata/chronograf#2998] opened 2018-03-15 20:48 UTC
Chronograf 1.4.2.3 > Alerting > Manage Tasks > Alert Rules

When first configuring Chronograf, if you create an InfluxDB connection as prompted and do not create an associated Kapacitor connection, opening the Alert Rules page displays "Loading Rules...". It never times out (that I've seen) and doesn't let you know that there is no Kapacitor connection.  It seems we should be able to detect the absence of a Kapacitor connection and notify the user with a meaningful error message.

**Comment by jaredscheib** [comment] 2018-03-15 20:52
dupe of https://github.com/influxdata/chronograf/issues/2458

**Comment by russorat** [comment] 2018-03-16 16:51
dupe

**Closed by russorat** 2018-03-16 16:51 UTC
