### ISSUE TITLE
CSV template variables replaced 

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#3330] opened 2018-04-30 18:18 UTC
![sad_template_variable](https://user-images.githubusercontent.com/1477539/39443044-525dde8c-4c81-11e8-8077-83094deb829c.gif)

**Comment by russorat** [comment] 2018-04-30 18:44
dupe of https://github.com/influxdata/chronograf/issues/3263 ?

**Closed by russorat** 2018-04-30 18:44 UTC
Labels: bug
