### ISSUE TITLE
Add annotations via kapacitor alerts

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2971] opened 2018-03-13 16:26 UTC

**Comment by goller** [comment] 2018-03-13 16:30
Here is how to add an annotation via curl:

```sh
CUR_UNIX_TIME=$(date +'%s')000000000 influx -database chronograf -execute "insert annotations,id=myid deleted=false,start_time=${CUR_UNIX_TIME}i,modified_time_ns=${CUR_UNIX_TIME}i,text=\"sp🚀 ces\",type=\"mytype\" ${CUR_UNIX_TIME}"
```

**Comment by russorat** [comment] 2018-03-14 16:50
we have a blog post in the works about how to do this, but it could be made much cleaner.

connect #2959

**Comment by russorat** [comment] 2018-07-16 17:12
dupe of #3628

**Closed by russorat** 2018-07-16 17:12 UTC
