### ISSUE TITLE
 Chronograf (1.7.10) Expected number or array but got string: d7ea00f4-8b4a-11e9-9d73-000c29de1f8a.

### ISSUE THREAD

**Issue by tfnick** [influxdata/chronograf#5205] opened 2019-06-10 07:42 UTC
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
Error: Expected number or array but got string: d7ea00f4-8b4a-11e9-9d73-000c29de1f8a.
    at j (http://192.168.1.195:8888/src.6c53cef1.js:3158:1898)
    at W.parseArray_ (http://192.168.1.195:8888/src.6c53cef1.js:3158:31911)
    at W.start_ (http://192.168.1.195:8888/src.6c53cef1.js:3158:35574)
    at W.updateOptions (http://192.168.1.195:8888/src.6c53cef1.js:3158:36541)
    at d.value (http://192.168.1.195:8888/src.6c53cef1.js:3218:4878)
    at xi (http://192.168.1.195:8888/src.6c53cef1.js:716:84251)
    at wi (http://192.168.1.195:8888/src.6c53cef1.js:716:79945)
    at ki (http://192.168.1.195:8888/src.6c53cef1.js:716:79561)
    at Ha (http://192.168.1.195:8888/src.6c53cef1.js:716:78073)
    at Object.enqueueSetState (http://192.168.1.195:8888/src.6c53cef1.js:716:47062)
```

we have string field and number field in Rule define UI，when I click a string field, then error happened.

**Comment by tfnick** [comment] 2019-06-10 07:44
Actually I want to count(some_string_field) here,But Once i click the string field the error happened

**Comment by timhallinflux** [comment] 2019-06-26 07:49
Duplicate of https://github.com/influxdata/chronograf/issues/5207

**Closed by timhallinflux** 2019-06-26 07:49 UTC
