### ISSUE TITLE
Alert History Load indefinitely

### ISSUE THREAD

**Issue by 12nick12** [influxdata/chronograf#5705] opened 2021-03-16 17:20 UTC
Hi, I am trying to log "Alert History" for my Kapacitor node within Chronograf and it just sits on the loading screen indefinitely. The server is running on RHEL7. Thanks.

**Comment by sranka** [comment] 2021-03-16 18:37
Thank you @12nick12 for posting an issue. Can you pls also include chronograf + kapacitor versions, browser version, screenshot of the page? Did you try to observe networking and console logs?

**Comment by 12nick12** [comment] 2021-03-18 15:40
chronograf.x86_64                   1.8.9.1-1                  @/chronograf-1.8.9.1.x86_64
kapacitor.x86_64                    1.5.7-1                    @/kapacitor-1.5.7-1.x86_64

Same issue happens on chrome and safari

![image](https://user-images.githubusercontent.com/17801285/111653943-abd0a800-87de-11eb-8e0f-f05a8216ed01.png)

I have not. Where should I look for errors?

**Comment by sranka** [comment] 2021-03-18 17:28
Thank you @12nick12 for the screenshot. I think that this is a duplicate of #5679 , which is already fixed in the next release. You can try it with the latest nightly build of chronograf, which is available at https://portal.influxdata.com/downloads/ .

The developer console and networking details are under Development tools, these can be opened in Chrome with Shift + ⌘ + I or Shift + CTRL + I. Any pending networking requests or errors in the console help with a technical description of the issue.

**Comment by 12nick12** [comment] 2021-03-22 15:18
I updated to the nightly and I'm still having the same issue. Below are the console logs

![rhq9nmpy](https://user-images.githubusercontent.com/17801285/112013394-6377f980-8b00-11eb-81f2-02e04417d7f1.png)

**Comment by 12nick12** [comment] 2021-03-22 15:19
This works directly with :8888 and when behind the apache reverse proxy :443 with valid SSL cert.

**Comment by sranka** [comment] 2021-03-22 17:50
I can't reproduce this locally, so I need more details from you, please follow these steps:
1. Open chronograf UI in Chome
2. Open Developer Console, switch to Networking tab
3. Reproduce this issue
4. Stop Recording Network Log
![image](https://user-images.githubusercontent.com/16321466/112034262-90e39800-8b3e-11eb-9511-3311ece40bfa.png)
5. Click on the proxy request that failed on 400 ... paste HTTP request and response herein
![image](https://user-images.githubusercontent.com/16321466/112034802-2bdc7200-8b3f-11eb-8faa-b4fb4f2cfd45.png)
![image](https://user-images.githubusercontent.com/16321466/112034999-6a722c80-8b3f-11eb-9cb9-cf117e2924b4.png)

**Comment by 12nick12** [comment] 2021-03-22 19:47
message: "received status code 403 from server: err: error authorizing query: chronograf not authorized to execute statement 'SELECT host, value, level, alertName FROM alerts WHERE time >= '2021-03-21T15:42:51-04:00' AND time <= '2021-03-22T15:42:51-04:00' ORDER BY time DESC', requires READ on chronograf"

I didn't know chronograf created a new db. That was the issue. I had to grant read on chronograf for chronograf

**Comment by sranka** [comment] 2021-03-22 19:51
I will keep this open, an error message should be better propagated to the user, and the details should be logged to the console

**Closed** 2021-03-23 11:51 UTC
