### ISSUE TITLE
Server does not save suffix and prefix for new cells

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#2567] opened 2017-12-13 01:21 UTC
1. Create new cell
2. Add query
3. Set type to any line graph
4. Add a prefix or suffix
5. Save
6. Refresh
7. 🙀

**Comment by nhaugo** [comment] 2017-12-18 21:22
Probably a dupe of #2595

**Comment by russorat** [comment] 2018-03-01 03:28
closed via #2845

**Closed by russorat** 2018-03-01 03:28 UTC
Labels: bug
