### ISSUE TITLE
Existing sources don't show meta service config option

### ISSUE THREAD

**Issue by dgnorton** [influxdata/chronograf#2164] opened 2017-10-26 14:30 UTC
After upgrading from `1.3.7` to `1.3.9`, existing data sources don't have the option to set a meta service. Only newly created sources have that option.

Old / existing data source...

![image](https://user-images.githubusercontent.com/209347/32058919-94d80dea-ba38-11e7-9b4c-20e1823754e2.png)

Newly added data source...

![image](https://user-images.githubusercontent.com/209347/32058945-a42d2280-ba38-11e7-98e7-0e351225f00e.png)

**Comment by nhaugo** [comment] 2017-10-26 14:37
Technically this is a dupe of https://github.com/influxdata/chronograf/issues/2000

**Closed by nhaugo** 2017-10-26 14:37 UTC
Labels: bug
