### ISSUE TITLE
Chronograf shows a error message in the alert history

### ISSUE THREAD

**Issue by Bakoos** [influxdata/chronograf#4342] opened 2018-09-03 22:33 UTC
operating system: . Ubuntu 18.04 LTS
Chronograf Version: 1.6 (built from source)

I have write a TickScript to send a e-mail alert.
After the alert was triggered I have get this error message in the alert history:
"A Chronograf error has occurred. Please report the issue here."
![image](https://user-images.githubusercontent.com/42868512/45002549-1aaad480-afd8-11e8-85ab-8b24d6d3fa4e.png)

How can I fix this?

My Script:

```
var groupBy = []

var whereFilter = lambda: TRUE

var m1 = stream
    |from()
        .database('telegraf')
        .retentionPolicy('autogen')
        .measurement('Raspi')
        .groupBy(groupBy)
        .where(whereFilter)
    |eval(lambda: "Innentemperatur")
        .as('value')

var m2 = stream
    |from()
        .database('telegraf')
        .retentionPolicy('autogen')
        .measurement('Raspi')
        .groupBy(groupBy)
        .where(whereFilter)
    |eval(lambda: "Aussentemperatur")
        .as('value')

var data = m1
    |join(m2)
        .as('m1', 'm2')

// Alert per E-Mail
data
    |alert()
        .crit(lambda: "m1.value" > "m2.value")
        .message('Die Innentemperatur {{ index .Fields "m1.value" }} ist kleiner als die Aussentemperatur {{ index .Fields "m2.value" }}')
        .id('Vergleich')
        .idTag('alertID')
        .levelTag('level')
        .messageField('message')
        .durationField('duration')
        .details('Vergleich Pascal')
        .email()
        .to('myMailAdress')

// Hinzufügen zu Chronograf DB
data
    |eval(lambda: float("m1.value"))
        .as('value')
        .keep()
    |influxDBOut()
        .create()
        .database('chronograf')
        .retentionPolicy('autogen')
        .measurement('alerts')
        .tag('alertName', 'CheckTwoValues')
        .tag('triggerType', 'threshold')

// Generiere Prozentuale Abweichung
data
    |eval(lambda: "m1.value" - "m2.value")
        .as('value_diff')
        .keep()
    |eval(lambda: (float("value_diff") / float("m1.value")) * 100.0, lambda: (float("value_diff") / float("m2.value")) * 100.0)
        .as('diff_percentage_m1', 'diff_percentage_m2')
    |influxDBOut()
        .measurement('diffs')
        .database('mydb')
        .create()

data
    |httpOut('output')
```

Thank you in advanced!

**Comment by russorat** [comment] 2018-09-04 16:54
@Bakoos thanks for reporting! we will take a look.

**Comment by russorat** [comment] 2018-09-06 23:17
@Bakoos we are having a hard time reproducing this. Do you mind opening the javascript console in Chrome dev tools (option+command+j) and adding what error message you are seeing?

**Comment by Bakoos** [comment] 2018-09-07 16:40
Hi Russorat

There are our Error Message's. I hope you can help us.

![image](https://user-images.githubusercontent.com/42868512/45231741-59d57000-b2cd-11e8-81e6-a4cc198baa98.png)

**Comment by russorat** [comment] 2018-09-07 18:28
@Bakoos thank you!

**Comment by jaredscheib** [comment] 2018-09-10 16:37
@Bakoos Since you're building from source, would you mind trying the following?

It's hard to know given the stack trace, but my guess is that the problem is in the Alerts Table component at `ui/src/alerts/components/AlertsTable.tsx` at the line
``className={`alert-history-table--td alert-level-${level.toLowerCase()}`}``, where it seems possible that `level` is `null`.

It looks like your TICKscript is actually forking `data` in a way that your `InfluxDBOut` does not have the attributes set for `level`, etc.

Note that in a default TICKscript, `data` with the modified attributes (such as `level`) is assigned to `trigger`, and then `trigger` is piped to InfluxDBOut:
```
var db = 'telegraf'

var rp = 'autogen'

var measurement = 'cpu'

var groupBy = []

var whereFilter = lambda: TRUE

var name = 'Untitled Rule'

var idVar = name

var message = ''

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var outputDB = 'chronograf'

var outputRP = 'autogen'

var outputMeasurement = 'alerts'

var triggerType = 'threshold'

var crit = 3

var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    |eval(lambda: "usage_idle")
        .as('value')

var trigger = data
    |alert()
        .crit(lambda: "value" > crit)
        .stateChangesOnly()
        .message(message)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .durationField(durationField)

trigger
    |eval(lambda: float("value"))
        .as('value')
        .keep()
    |influxDBOut()
        .create()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement(outputMeasurement)
        .tag('alertName', name)
        .tag('triggerType', triggerType)

trigger
    |httpOut('output')
```

Could you let me know if fixing this makes your status page work, @Bakoos? Thank you for reporting this.

--
Additionally, @russorat would you like a custom error message that indicates this type of issue to the user, in this case, as a resolution to this issue?

**Comment by russorat** [comment] 2018-09-10 18:30
re: would you like a custom error message that indicates this type of issue to the user, in this case, as a resolution to this issue?
our component should not crash due to something a user has done. we shouldn't explicitly have an error message for this, our component should be robust enough to not crash.

**Comment by jaredscheib** [comment] 2018-09-10 18:38
Word, so how do you want this robustness to show up? If not display a custom error message, what should the component do in the case that there is (what appears to be) insufficient tags (such as `label` being `null`) on a data point? Display the string `null` under `label`?

**Closed** 2018-09-11 15:12 UTC
Labels: bug, regression
