### ISSUE TITLE
 Chronograf (1.7.7) o is not a function

### ISSUE THREAD

**Issue by antoine-briand** [influxdata/chronograf#5054] opened 2019-01-23 17:30 UTC
# What browser are you using (name and version)?

Chrome Version 71.0.3578.98

# What operating system are you using?

Mac OS X for the client
Centos 7 where all the stack is installed

# Please describe what you were trying to do when you encountered this error:

I was just following the "getting started" instructions of chrongraf UI, after installing it with this tutorial : https://www.digitalocean.com/community/tutorials/how-to-monitor-system-metrics-with-the-tick-stack-on-centos-7

It looks like a javascript error, when I type the credentials for the Kapacitor connection. Skipping this step allows me to finish the setup and use Chronograf (I just had to setup the Kapacitor connection after).

- InfluxDB shell version: 1.7.3
- Telegraf 1.9.3 (git: HEAD 6ad8c8b0)
- Kapacitor OSS 1.5.1 (git: HEAD 89828ffff6cf5cd4cb2b34bf883e134395f734de)
- Chronograf v1.7.7

```
TypeError: o is not a function
    at d.<anonymous> (http://34.76.91.123:8888/src.216c1ae9.js:4691:3998)
    at pl (http://34.76.91.123:8888/src.216c1ae9.js:716:45572)
    at dl (http://34.76.91.123:8888/src.216c1ae9.js:716:45322)
    at xi (http://34.76.91.123:8888/src.216c1ae9.js:716:84392)
    at wi (http://34.76.91.123:8888/src.216c1ae9.js:716:79945)
    at ki (http://34.76.91.123:8888/src.216c1ae9.js:716:79561)
    at Le (http://34.76.91.123:8888/src.216c1ae9.js:716:90853)
    at We (http://34.76.91.123:8888/src.216c1ae9.js:716:10444)
    at Fn (http://34.76.91.123:8888/src.216c1ae9.js:716:30800)
    at Si (http://34.76.91.123:8888/src.216c1ae9.js:716:85578)
```

    
<img width="1920" alt="capture d ecran 2019-01-23 a 18 25 32" src="https://user-images.githubusercontent.com/4669715/51625157-c1b6eb00-1f3c-11e9-9d4d-69d0b3095f15.png">

**Comment by russorat** [comment] 2019-02-06 23:23
probably a dupe of https://github.com/influxdata/chronograf/issues/5055

**Comment by Seungwoo321** [comment] 2019-02-12 17:18
change your config file 

/etc/influxdb/influxdb.conf
```
# bind-address = "127.0.0.1:8088" ->  bind-address = "0.0.0.0:8088"
```

**Comment by russorat** [comment] 2019-02-13 20:03
@Seungwoo321 this is fixed with https://github.com/influxdata/chronograf/issues/5060

i don't think the conf file would have anything to do with this issue.

**Closed by russorat** 2019-02-13 20:03 UTC
Labels: bug
