### ISSUE TITLE
 Chronograf (1.8.2) Invalid size returned for cell 2 of value undefined

### ISSUE THREAD

**Issue by dagwieers** [influxdata/chronograf#5469] opened 2020-04-30 10:31 UTC
> What browser are you using (name and version)?

Chrome Version 80.0.3987.132 (Official Build) (64-bit)

> What operating system are you using?

Fedora release 31 (Thirty One)

> Please describe what you were trying to do when you encountered this error:

Trying to plot raw values in a normal graph. (It was using mean(), but I removed it)

```
Error: Invalid size returned for cell 2 of value undefined
    at i.value (http://localhost:8888/src.9f900c48.js:2850:1411)
    at i.value (http://localhost:8888/src.9f900c48.js:2850:2700)
    at r.value (http://localhost:8888/src.9f900c48.js:2854:2359)
    at f.value (http://localhost:8888/src.9f900c48.js:2925:12908)
    at f.value (http://localhost:8888/src.9f900c48.js:2925:11170)
    at Ba (http://localhost:8888/src.9f900c48.js:717:65834)
    at ja (http://localhost:8888/src.9f900c48.js:717:65629)
    at $a (http://localhost:8888/src.9f900c48.js:717:69008)
    at oo (http://localhost:8888/src.9f900c48.js:717:91055)
    at uo (http://localhost:8888/src.9f900c48.js:717:91442)
```

**Comment by russorat** [comment] 2020-05-08 15:49
@dagwieers thanks for this. could you update to chrono 1.8.4 to see if this issue still exists?

**Comment by sranka** [comment] 2020-06-21 06:21
This error is thrown from a Table Grid component. Closing this in favor #5347, the root cause is the same.

**Closed by sranka** 2020-06-21 06:21 UTC
Labels: bonitoo, kind/bug
