### ISSUE TITLE
If chronograf user doesn't have read permissions to any db, influxdb admin page is blank

### ISSUE THREAD

**Issue by perzizzle** [influxdata/chronograf#5531] opened 2020-07-07 14:05 UTC
We run chronograf as a service account with read only permissions to databases. If a new database is created and the chronograf user doesn't have permissions to it, the influx db admin page becomes blank even though it has permissions to all other databases. The chronograf logs contain (where mydb is the db the user doesn't have permissions to).

chronograf: time="2020-07-06T18:03:38-05:00" level=error msg="Error message received status code 403 from server: err: error authorizing query: chronograf not authorized to execute statement 'SHOW RETENTION POLICIES ON mydb'" component=server http_status =400

I would expect the admin page to still show the databases the user does have permissions to.

**Comment by russorat** [comment] 2020-07-17 15:25
@perzizzle thanks for reporting. looks like a bug.

**Comment by timhallinflux** [comment] 2020-12-08 20:24
reproduce...and determine if an issue needs to be filed for InfluxDB.

**Comment by timhallinflux** [comment] 2020-12-08 23:34
I attempted to reproduce this today.  I was unable to do so. I believe this has been resolved in a subsequent release.

@perzizzle are you running InfluxDB OSS or Enterprise.  Are you still having this issue?

**Comment by perzizzle** [comment] 2020-12-09 13:59
We are running the enterprise version and are on the latest version. I can try to reproduce again.

**Comment by sranka** [comment] 2020-12-14 12:56
I can't reproduce this either. Anyway, the implementation first lists the databases using `SHOW DATABASES` query, then retention policies are retrieved per every database using `SHOW RETENTION POLICIES ON "<db>"` for every database. If any of the second queries fails, the whole list fails and the UI shows then a blank screen. I can't tell why a database is shown and its retention policies are not, it is a state that the UI does not expect to be common. Anyway, an error in the second query can safely cause to ignore the database in the returned list.

**Comment by perzizzle** [comment] 2020-12-15 19:04
Did you mean you CAN reproduce this issue? That seems to be describing the same behavior I was seeing. If the user doesn't have permissions to any database the whole UI is empty.

**Comment by sranka** [comment] 2020-12-15 19:14
I can't reproduce, but I can imagine what happened ... so I prepared the fix.

**Comment by timhallinflux** [comment] 2020-12-15 19:41
I couldn't reproduce using InfluxDB OSS and the latest version of Chronograf.  However, the Enterprise permissions model is certainly more complex and more fine grained. 

I setup a read-only user using InfluxDB Enterprise through Chronograf. 
Doing so, causes the InfluxDB Admin panel to spin...and not render.

It also prevents the db.rp's from loading the Data Explorer...so that needs a look as well.  

From the docs, Read-only users should have the following permissions:
https://docs.influxdata.com/enterprise_influxdb/v1.8/features/users/
`
ShowFieldKeysStatement, 
ShowMeasurementsStatement, 
ShowSeriesStatement, 
ShowTagKeysStatement, 
ShowTagValuesStatement, 
ShowRetentionPoliciesStatement
`

**Comment by sranka** [comment] 2020-12-15 20:04
It is [documented that Create Database](https://docs.influxdata.com/chronograf/v1.8/administration/managing-influxdb-users/#createdatabase) permission is required to view Dashboards, Data Explorer, and Databases on the Admin page.

**Comment by timhallinflux** [comment] 2020-12-16 03:26
hmmmm.... but: https://docs.influxdata.com/chronograf/v1.8/administration/managing-influxdb-users/#readdata  says that is has `show retention policies`?  So it is a little strange....

**Comment by sranka** [comment] 2020-12-16 04:21
@timhallinflux thank you, I think that I understand the reported behavior now. When a new database is created, the service account has no permissions to the new database. Administration UI fails because of that, but it must not. I'll also inspect the situation in Data Explorer and possibly include fixes in the PR.

**Closed** 2020-12-17 12:49 UTC
Labels: area/auth, kind/bug
