### ISSUE TITLE
Alert Endpoints don't work in Kapacitor Sources

### ISSUE THREAD

**Issue by pauldix** [influxdata/chronograf#357] opened 2016-11-04 15:51 UTC
Configure your Kapacitor and then you don't see anything but the drop down in Alert Endpoints. Try changing the selected option on the drop down or refreshing the page and it still doesn't work. There's nothing in the js console to indicate an error. I followed the URL for the Kapacitor config and that comes up.

![screen shot 2016-11-04 at 11 47 39 am](https://cloud.githubusercontent.com/assets/4331/20012281/01aca5d8-a285-11e6-92a6-24e584375a7b.png)

**Comment by nhaugo** [comment] 2017-01-05 19:28
Dupe of #371

**Closed by nhaugo** 2017-01-05 19:28 UTC
