### ISSUE TITLE
[TICKScript Editor] Could not collect kapacitor logs

### ISSUE THREAD

**Issue by w4tsn** [influxdata/chronograf#5050] opened 2019-01-21 12:27 UTC
Maybe related to #3415.

I'm using Chronograf v1.7.5 and kapacitor 1.5.1 docker versions. When opening a tickscript in the editor it shows the error 'Could not collect kapacitor logs'. I have no BASE_PATH configured. As far as I know, this feature did not work for me from the beginning. Could be a misconfiguration. I'm struggling to debug this and I couldn't find anything regarding this in the docs.

How do I troubleshoot this? What is causing this issue? Any ideas?

In Chronograf I've configured the capacitor connection with the URL `http://kapacitor:9092/` which is working over an internal docker network. Both services are residing in this network.

**Comment by xxwassyxx** [comment] 2019-01-25 16:11
I am actually seeing something very similar myself. If I set a lognode I can see the output in the containers output but not in the viewer.

**Comment by xxwassyxx** [comment] 2019-01-25 17:22
some troubleshooting but this is possibly an issue with the browser not being able to reach that url? so from my tests I can tell chronograf can indeed reach kapacitor and get the logs.

from inside a chronograf container - 
curl kapacitor-kapacitor:9092/kapacitor/v1preview/logs\?task=<yourtask>

and log output occurs as expected. However looking at how this is stitched together from
https://github.com/influxdata/chronograf/pull/3464
the browser needs to make a similar call. Which naturally in a kubernetes environment is not going to be exposed by deault and the url is going to be different. 

Am I on the right track?

**Comment by sdicataldo** [comment] 2019-02-18 10:40
Hi, update about the bug:
When a kapacitor is connected using the chronograf interface, even if all the functionalities privided by the chronograf interface work well, there is a bug on retrieving the logs generated with the node log() is added.
See the screenshot below

![schermata 2019-02-18 alle 10 55 17](https://user-images.githubusercontent.com/47741681/52945434-02eebf00-3372-11e9-92d6-1b04cff62453.png)

The issue is returned only using morzilla firefox browser, no when chrome is used.

Data:
Firefox Quantum 64.0.2 (64 bit)
Chronograf v1.6.2
Kapacitor v1.5.1

Open source tick stack used.

At this stage is not possible visualize the “200 Most Recent Logs” related to a tickscript and the error “Could not collect kapacitor logs” is always returned when the tickscript data are expanded

Could someone have a look or give a feedback about?

Thanks

**Comment by sdicataldo** [comment] 2019-02-18 10:56
Update: The issue look fixed with a browser restart.
[xxwassyxx](/xxwassyxx) your analysis was correct. Chronograf interface make a call against the chronograf backend that redirect the request to kapacitor.

**Comment by w4tsn** [comment] 2019-05-02 09:34
I'm not sure if this is the same issue I'm facing. This problem persists in a production environment for half a year by now. Currently we are debugging / getting the logs directly from the server, since Chronograf is not able to get them. This is quite annoying. What does a browser restart and the log() node have to do with all of this? For me it seems more a configuration / firewall issue or a bug in chronograf. I'm a bit lost here on finding out what it is.

**Comment by cruscio** [comment] 2019-07-31 14:24
I'm seeing similar issues in both Chrome and Firefox. Kapacitor has debug logging enabled but nothing shows up in Chronograf TICKScript logs. There aren't any bad requests in the browser developer console and there isn't anything interesting in the chronograf logs. Not sure where the breakdown in communication is, but it's somewhere.

**Comment by cruscio** [comment] 2019-10-29 14:55
I'd rather you not close this stalebot. Also, more constructively, I'm pretty sure this has something to do with the use of a reverse proxy. Haven't had time to trace exactly what's happening though.

**Comment by cruscio** [comment] 2020-01-27 15:31
::_glares at stalebot_::

**Comment by sinistram** [comment] 2020-03-30 00:31
I had the same problem. Only kapacitor service restart helps.

**Comment by kannappan-v** [comment] 2021-01-13 17:15
same issue

**Comment by sranka** [comment] 2021-08-31 03:42
Chronograf 1.8.10 fixed #5641 that might have caused the issue described herein. Chronograf 1.9.0 also adds more UI fixes that can change the situation. Pls try to reproduce this with chronograf 1.9.0 and reopen the issue if it is still the same.

**Closed by sranka** 2021-08-31 03:42 UTC
