### ISSUE TITLE
Enhance dashboards api with 'view' option to cut down on response size

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3594] opened 2018-06-07 20:40 UTC
Currently, when a single dashboard page loads, it retrieves all dashboards from the server simply in order to populate the values and links for the Dashboard Switcher component. It's unnecessary and wasteful to user data consumption, and if an organization has many dashboards, it may be a slower response eventually as well.

We could implement a straightforward "view" API for `/dashboards`, such as `/dashboards?view=names` that would send back just the names and links for all dashboards. This would be cleaner frontend code and a much smaller response size.

cc @goller for reference

**Comment by nhaugo** [comment] 2018-07-02 20:18
Dupe of https://github.com/influxdata/chronograf/issues/3602

**Closed by nhaugo** 2018-07-02 20:18 UTC
Labels: chore, performance
