### ISSUE TITLE
Allow user to see query on the pre-canned dashboards

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#2857] opened 2018-02-26 22:55 UTC
For pre-canned dashboards, allow the end-user to see the query that is being used.

Perhaps an icon could be placed on each cell which would allow the user to click and display the query. Also provide a mechanism for the user to easily copy the query itself without highlighting and using cmd+c.  

This would allow the user to then paste the query into the data explorer or dashboard cells....and modify the query params to rapidly build/modify.

**Comment by nhaugo** [comment] 2018-03-19 17:56
@russorat is this now a dupe of #2962

**Closed** 2018-03-19 18:05 UTC
Labels: pm/consumability
