### ISSUE TITLE
[1.3.6.0] Single stat selection broken in Custom Dashboards

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/chronograf#1847] opened 2017-08-09 18:09 UTC
![gif](http://g.recordit.co/ZUDC0sLQrF.gif)

**Comment by jaredscheib** [comment] 2017-08-15 01:36
Looks like a retro-dupe of #1865, nay? Closing since we published a hotfix. Thanks, @jackzampolin 😺

**Closed by jaredscheib** 2017-08-15 01:36 UTC
