### ISSUE TITLE
Minified React error #31 when viewing Data Explorer tab

### ISSUE THREAD

**Issue by yosemitebandit** [influxdata/chronograf#1476] opened 2017-05-12 23:26 UTC
* OS: Mac 10.12.4
* running `quay.io/influxdb/chronograf:latest` via docker
* I can connect to a source (in my case, an InfluxDB instance running on AWS) and I can view other tabs.  But the UI freezes with [React error 31](https://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bname%2C%20framesToPop%7D&args[]=) if I click the Data Explorer tab

For what it's worth, I do not have telegraf running -- I am adding random test data to the InfluxDB instance via the HTTP API.  My "Host List" is empty in chronograf.  I was hoping to use chronograf to visualize my custom data.

**Comment by goller** [comment] 2017-05-15 02:28
Hey there @yosemitebandit , thanks for writing!  I'll start working on reproducting it.

**Comment by goller** [comment] 2017-05-15 02:32
Oh, @yosemitebandit while I'm reproducing, would you try the release 1.3.0 container here: `docker pull chronograf` ?

**Comment by goller** [comment] 2017-05-15 03:23
Hey @yosemitebandit I tried reproducing the issue you have above in Firefox and chrome with `docker pull chronograf` and `docker pull quay.io/influxdb/chronograf:latest` without getting the error.

Here was my setup:

```sh
docker run --name influxdb   influxdb
docker run --name chronograf  --link influxdb  chronograf
```

I added `http://influxdb:8086` as the data source for chronograf and then added a bit of data:
```sh
curl -i -XPOST http://192.168.99.100:8086/query --data-urlencode "q=CREATE DATABASE mydb"
 curl -i -XPOST 'http://192.168.99.100:8086/write?db=mydb' --data-binary 'cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000'
curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu_load_short,host=server02 value=0.67
cpu_load_short,host=server02,region=us-west value=0.55 1422568543702900257
cpu_load_short,direction=in,host=server01,region=us-west value=2.0 1422568543702900257'

```

After this I was able to get to data explorer within chronograf and see it ok.  

SO!  Would you try the following?

1. Try running incognito mode in the browser and see if it is still a problem
2. Try to use the 1.3.0 release and see if it works (either `docker pull quay.io/influxdb/chronograf:1.3.0` or `docker pull chronograf`)

**Comment by jademcgough** [comment] 2017-05-15 04:33
This may be related to https://github.com/influxdata/chronograf/issues/1465 - definitely try opening the data explorer in incognito mode, my hunch is that this is a localStorage issue.

**Comment by goller** [comment] 2017-05-15 05:05
Ok I was able to get this issue.  I'm not entirely sure how.  I would click around the hosts and then to the data explorer and back.  At some point I got that error:

<img width="808" alt="image" src="https://cloud.githubusercontent.com/assets/1922921/26043375/35af1fd2-3902-11e7-9ce5-6f7dcea4bb3e.png">

**Comment by goller** [comment] 2017-05-15 22:19
OK! @cryptoquick and I figured it out.  Basically, the localstorage would become corrupted if an error *object* was thrown from AJAX because this code (https://github.com/influxdata/chronograf/blob/master/ui/src/shared/actions/timeSeries.js#L35) assumed it would be a string.

The fixes are here : https://github.com/influxdata/chronograf/pull/1458  

We plan on releasing this week and this should be fixed.  Thank you @yosemitebandit again !

**Comment by yosemitebandit** [comment] 2017-05-16 16:45
thanks @goller -- look forward to trying the new release!

**Closed** 2017-05-18 15:32 UTC
Labels: bug, delivered, needs more info

**Comment by theone3nu** [comment] 2018-12-15 20:30
still i am getting this error in IE 11.  Can any one tell me How to fix this?
