### ISSUE TITLE
No hosts registered under host lists tab in Chronograf

### ISSUE THREAD

**Issue by asanami** [influxdata/chronograf#2830] opened 2018-02-20 20:42 UTC
It looks like the hosts are only registered if the database configured in telegraf is 'telegraf' and under the autogen retention policy. If this is set to an alternative database or under an alternative retention policy, then the host doesn't appear in the list.

**Comment by russorat** [comment] 2018-02-20 23:06
connect #682 

thanks for the report @asanami . we will tackle this as part of the larger host list page redesign.

**Comment by russorat** [comment] 2018-09-28 16:37
@exabrial we added the ability to define a default rp in the connection relatively recently, so if that's what you are seeing, this is probably a regression bug. we will take a look.

**Comment by kanupriya15025** [comment] 2019-02-25 12:38
has it been fixed?

**Comment by adeleglise** [comment] 2019-03-01 10:39
Same here, do you have any news ?

**Comment by exabrial** [comment] 2019-03-01 18:49
It hasn't, just use the workaround though. If you need to set a retention policy, do it at the command influxdb line:

It should be obvious this is a destructive operation:

```
drop retention policy autogen on chronograf;
create retention policy "autogen" on chronograf duration 45d replication 1 default;
drop retention policy autogen on telegraf;
create retention policy "autogen" on telegraf duration 45d replication 1 default;
```

**Comment by pokemane** [comment] 2019-10-30 16:41
Could this be reopened, or could we get an update on whether this is addressed in influx 2.x at least?

**Comment by exabrial** [comment] 2019-11-01 21:04
This started working for us. I believe the issue was using a non-default Influx database name

**Comment by russorat** [comment] 2019-11-01 22:23
@pokemane you will not have this issue in 2.x.

I will reopen and consider it for the next maintenance release.

**Comment by goller** [comment] 2019-11-06 16:07
I'm not super sure, but, it looks like the host page respects the templates:

https://github.com/influxdata/chronograf/blob/bb4f123bfd4c533604f5c4e7b4e3cb4a0d6e645c/ui/src/hosts/apis/index.ts#L60

Looks like `:db:` and `:rp:`

Perhaps, this will be as easy as adding template variables to the host page?

**Comment by desa** [comment] 2019-11-06 17:06
I believe that this is actually a feature request. I'll put it in our next feature baring release.

**Comment by desa** [comment] 2020-01-06 18:14
Host list page should have configurable database on this page
![Screenshot 2020-01-06 10 14 12](https://user-images.githubusercontent.com/1477539/71838309-5db60580-306d-11ea-80e9-051f3f746ac4.png)

**Comment by russorat** [comment] 2020-01-14 18:57
@asanami we are working through this right now, but we cannot reproduce this issue.

For some background, the host page queries the data source you are currently connected to and the url has the id of the connection in it (`http://localhost:8888/sources/4/hosts` for example).

When you configure the connection to that host, you specify the database (usually telegraf, but sounds like it's custom in your case):
![image](https://user-images.githubusercontent.com/4805997/72372790-e2cb9b00-36bb-11ea-9add-a69097315779.png)
Here, I configured them to be `not_telegraf` and `not_autogen` respectively.

Then on the host list page, we use those values in the queries we execute:
![image](https://user-images.githubusercontent.com/4805997/72372850-068ee100-36bc-11ea-9fba-327ebd278fa0.png)

You will see hosts that are not in that specific retention policy because the way the InfluxQL meta queries work, they run at a DB level, not a retention policy level.

For reference, here are the queries we run and you can see they have the right DB and RP substituted in:
```
SELECT mean("usage_user") FROM "not_telegraf"."not_autogen"."cpu" WHERE "cpu" = 'cpu-total' AND time > now() - 10m GROUP BY host;
SELECT mean("load1") FROM "not_telegraf"."not_autogen"."system" WHERE time > now() - 10m GROUP BY host;
SELECT non_negative_derivative(mean(uptime)) AS deltaUptime FROM "not_telegraf"."not_autogen"."system" WHERE time > now() - 1m0s * 10 GROUP BY host, time(1m0s) fill(0);
SELECT mean("Percent_Processor_Time") FROM "not_telegraf"."not_autogen"."win_cpu" WHERE time > now() - 10m GROUP BY host;
SELECT mean("Processor_Queue_Length") FROM "not_telegraf"."not_autogen"."win_system" WHERE time > now() - 10s GROUP BY host;
SELECT non_negative_derivative(mean("System_Up_Time")) AS winDeltaUptime FROM "not_telegraf"."not_autogen"."win_system" WHERE time > now() - 1m0s * 10 GROUP BY host, time(1m0s) fill(0);
SHOW TAG VALUES WITH KEY = "host" WHERE TIME > now() - 10m;
```

We will not be adding any additional features to this page for source selection.

**Comment by timhallinflux** [comment] 2020-12-04 02:28
This works as designed.  I think the core issue was the misunderstanding of where the configuration for the Host List page (which is drawn from the connection configuration where you can set the name and RP of the database).  The Host List page essentially uses those two pieces of information to render.  If the underlying host data is not present within the specified database, the page will not render.

**Closed by timhallinflux** 2020-12-04 02:28 UTC
Labels: invalid
